- clevercloud/http.json
- clevercloud/python.json
Personnalisation du déploiement pour Clever Cloud
Pour ajouter les commandes de déploiement de DJANGO (migrate et collectstatic), mettre en cache les dépendances, et forcer le HTTPS et l'encodage.
En créant les fichiers `http.json` et `python.json` que Clever Cloud sait interpréter.
> Personnalisation du déploiement Clever Cloud

- lacommunaute/templates/forum_conversation/partials/post_form.html
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- Désactiver l'utilisation de la signature lors des publication
- Signature : pour ne pas à avoir à gérer leur affichage dans les nouveaux threads
- Signature : surcharge des templates machina
> Désactiver l'utilisation de la signature lors des publication

- config/settings/base.py
Correction de la configuration du stockage S3
Le téléversement des fichiers ne fonctionnent pas en production.
La variable d'environnement `CELLAR_ADDON_HOST` n'indique pas le protocole. J'ajoute donc une variable d'env `CELLAR_ADDON_PROTOCOL` avec une valeur par défaut : https.
> Correction de la configuration du stockage S3

- lacommunaute/forum/tests.py
- lacommunaute/templates/forum/forum_detail.html
cf titre
pour faciliter l'obtention de l'URL sans passer par l'équipe de dev ni l'interface d'admin
Vérifier les droits `can_approve_posts` de l'utilisateur et afficher l'URL en bas de page
> Invitation des membres d'une communauté - Bonus - afficher le lien d'invitation pour les animateurs de la communauté

- lacommunaute/forum/models.py
- lacommunaute/templates/pages/statistiques.html
- lacommunaute/www/pages/views.py
cf titre
Les statistiques des communautés ne prennent pas en compte les statistiques des enfants.
Ajout des pk des enfants dans le filtre des sujets, des posts et des membres
Le nombre de membres est également masqué pour les communautés publiques car il n'y a pas d'adhésion dans ce cas.
> Statistiques : prise en compte de l'arborescence des communautés

- Makefile
Mise à jour du `Makefile`, remplacement de l'appel à `shell` par l'appel à `shell_plus`
> Appeler la commande 'shell_plus' dans l'alias 'make console'

- lacommunaute/forum/models.py
🎸 les annonces doivent être prise en compte pour que la courbe corresponde aux compteurs de machina.
🪲 Suppression de l'exclude pour la prise en compte des annonces
> Page statistique : les sujets de type annonces doivent être compte

- .github/pull_request_template.md
- README.md
- lacommunaute/forum/tests.py
- lacommunaute/templates/forum/forum_detail.html
🎸 Corrections rapides à droite à gauche
🪲 Correction du lien d'invitation à rejoindre une communauté privée
🪲 Correction d'une petite faute dans le template de PR
🪲 Petite modification de la procédure de création d'une communauté privée pour qu'elle soit directement en privée et attachée au bon groupe de membres
🦺 Le lien d'invitation doit impérativement pointer vers le formulaire pour rejoindre la communauté, ainsi, si la personne n'ai pas connectée, elle est redirigée vers la landing avec la bonne URL de retour. Si elle est connectée, elle peut directement rejoindre la communauté. À mon avis, ce lien a été oublié quand on a mis en place l'URL de retour et pose désormais problème.
> Corrections rapides

- lacommunaute/templates/forum/forum_detail.html
🎸 Masquer la description de la communauté dans la page `forum_detail` si la description n'est pas renseignée
🦺 pas de test, assumé
> Masquer la description de la communauté si elle est vide

- lacommunaute/templates/board_base.html
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum/index.html
- lacommunaute/templates/layouts/base.html
- lacommunaute/templates/pages/accessibilite.html
- lacommunaute/templates/pages/contact.html
- lacommunaute/templates/pages/home.html
🎸 Cf titre et ticket https://www.notion.so/Mettre-en-place-le-SEO-des-sujets-des-communaut-s-ouvertes-pour-r-f-rencement-naturel-2b444af05b8345488b5ddcc310616d36
🎢 Ajout de contenu pour les balises title et meta-description dans les pages les plus importantes 
@vincentporte Apparemment la variable `{{ site.name }}` et/ou `{{ MACHINA_FORUM_NAME|default:"Forum" }}` ne retourne rien. J'imagine que ça se configure le BO de machina/django et que tu pourrais remedier a ça ?
> Quelques rapides optimisations des meta pour le SEO

- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
🎸 Les infos d'édition des `Post` et des `Topic` surchargent l'UI sans apporter de réelle valeur. Elles sont masquées dans la vue `forum_detail` et `topic_detail`. 
🦺 ces informations pourront être remises à disposition des animateurs ultérieurement
> Masquer les informations d'édition des Topic et des Post

- lacommunaute/templates/pages/statistiques.html
🎸 J'avais récemment voulu faire du propre en déplaçant l'appel de chart.js dans la zone dédiée `{% block extra_js %}`. Sauf que j'ia constaté ce matin que les statistiques ne s'affichaient plus en prod. Et pour cause, je n'avais pas déplacé les déclarations d'instance de `new Chart` dans la même zone .
🪲 Correction du bug qui se trouve entre la cahise et le clavier.
En même temps j'ai une excuse, je dois le faire l'aveugle, car les statistiques ne s'affichent pas chez moi, en local
> Correction de l'affichge des statisitiques

- lacommunaute/templates/forum_conversation/forum_attachments/attachments_detail.html
🎸 Les pièces jointes de type image sont affichées dans le texte du message. Ne plus faire apparaitre le lien dans la liste des pièces jointes
🦺 Le titre "Pièces jointes" et sa ligne de séparation sont mis en commentaires le temps de trouver une solution simple pour :
- les afficher quand il y a des pièces jointes de type autre que image
- ne pas les afficher quand les pièces jointes sont toutes de type image
> Masquer le lien vers les images dans les pièces jointes des posts

- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_member/forum_profile_detail.html
- lacommunaute/templates/partials/header_nav_primary_items.html
- lacommunaute/www/forum_member/tests.py
- lacommunaute/www/forum_member/urls.py
- lacommunaute/www/forum_member/views.py
🎸 Donner accès à la page de profil de l'utilisateur connecté
🎸 Lui permettre de mettre à jour son profil avec une photo et une signature
🎸 Mettre à jour les liens de navigation
🦺 Surcharge des vues et des urls machina d'origine pour `ForumProfileDetailView` et `ForumProfileUpdateView`
Mise à jour du lien dans le menu utilisateur
Simplification de la page de profile
> Rediriger l'utilisateur vers sa page de profil après la mise à jour de son profil

- .pre-commit-config.yaml
🎸 Objectif : dissocier les montées de version des dépendances des évolutions fonctionnelles
🎨 changement nécessitant une mise à jour de la documentation.
🦺 La commande `poetry lock`, ou le script `update_dependancies` devront être executées régulierement, independamment des autres PR. Idéalement en début de releases.
> Settings: retrait du hook poetry-lock de precommit

- .github/workflows/changelog-generator.yml
🎸 Generation automatique du journal des changements lors de la création d'une nouvelle release github
🥁 Changement de rupture (modification ou caractéristique qui empêcherait une fonctionnalité existante de fonctionner comme prévu)
🎨 changement nécessitant une mise à jour de la documentation.
🦺 Ajout la clé `CHANGELOG_GITHUB_TOKEN` dans les secrets du repo.
🦺 POUR TEST
> Integration Continue : Generation du Journal des Changements

- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum/forum_list.html
- lacommunaute/templates/forum_conversation/partials/post_feed.html
- lacommunaute/templates/forum_conversation/partials/posts_list.html
- lacommunaute/templates/forum_conversation/partials/topic_content.html
- lacommunaute/templates/forum_conversation/post_preview.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/utils/templatetags/str_filters.py
- lacommunaute/utils/tests.py
🎸 Convertir automatiquement les url en liens actionnables dans les descriptions des communautés
🎸 Convertir automatiquement les url en liens actionnables dans les contenus des posts
🎸 Les liens sont raccourcis à 30 charactères, et emporte un `target=_blank` pour forcer leur ouverture dans une nouvelle fenetre.
Fil d'actualités d'une communauté
Liste des communautés / sous-communautés
> Convertir automatiquement les url dans les descriptions des communautés et dans les posts

- lacommunaute/static/stylesheets/itou_communaute.scss
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/forum_member/moderator_profiles.html
🎸 Correction de la mise en forme du  topic-thumbnail
🪲 Correction de templating et css
Avant
Apres
> Correction de la mise en forme de l'avatar topic-thumbnail

- lacommunaute/forum/factories.py
- lacommunaute/forum/tests.py
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum/forum_list.html
- lacommunaute/templates/forum/funnel.html
- lacommunaute/templates/forum/moderator_engagement.html
- lacommunaute/templates/forum_conversation/forum_polls/topic_list_poll_detail.html
- lacommunaute/templates/forum_conversation/forum_polls/topic_list_poll_vote_form.html
- lacommunaute/templates/forum_conversation/partials/post_feed_form_collapsable.html
- lacommunaute/templates/forum_conversation/partials/post_upvotes.html
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- lacommunaute/templates/forum_conversation/partials/topic_likes.html
- lacommunaute/templates/forum_conversation/post_create.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/forum_member/forum_profile_detail.html
- lacommunaute/templates/forum_member/moderator_profiles.html
- lacommunaute/templates/forum_member/profiles.html
- lacommunaute/templates/pages/home.html
- lacommunaute/templates/partials/breadcrumb.html
- lacommunaute/templates/partials/header_nav_primary_items.html
- lacommunaute/www/forum_conversation/tests.py
- lacommunaute/www/forum_conversation/urls.py
- lacommunaute/www/forum_member/tests.py
🎸 ajout des actions `contribute`  sur la création de `topic` et de `post`
🎸 ajout des actions `view`  des pages de `topic`, `forum`, `profile`, `forum_profiles`
🎸 correction de l'action `vote` : ajout de `data-matomo-option`
🎸 correction de l'action `upvote` : rennomage de l'option en `downvote`
🎢 MISE A JOUR fonctionnalité
🦺 remplacement de l'url `machina` `forum_member:profile` par l'url surchargée `members:profile`
🦺 renommage de l'url `forum_conversation_extension:comment_topic` par `forum_conversation_extension:post_create` pour plus de consistence
> Ajout/Mise à jour des actions Engagement envoyées à Matomo

- lacommunaute/www/forum_member/tests.py
- lacommunaute/www/forum_member/urls.py
- lacommunaute/www/forum_member/views.py
🎸 La vue `members:profiles` liste l'intégralité des membres de la plateforme. Cette vue n'est référencée dans aucune autre vue => suppression
🥊 suppression code mort
> Suppression de la vue de tous les membres du Forum

- lacommunaute/utils/stats.py
🎸 trier les périodes par ordre croissant dans les graphes de statistiques
🦺 correction rapide, ne resout pas le sujet des périodes sans donnée.
> [fix urgent] Stats - ordonner les périodes pour les graphes

- lacommunaute/forum/models.py
- lacommunaute/utils/stats.py
- lacommunaute/utils/tests.py
🎸 Formatter les dates après leur tri
🦺 Ce patch devra être modifié pour gérer les périodes sans données entre la plus ancienne période et maintenant
### copies d'écrans
Par mois
Par semaine
> FIX PR139 - Stats - ordonner les périodes pour les graphes

- lacommunaute/templates/forum_conversation/post_preview.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/forum_member/forum_profile_detail.html
- lacommunaute/templates/partials/footer.html
Réduction de largeur de colonne du post-content
https://www.notion.so/Ne-pas-afficher-le-texte-du-sujet-sur-toute-la-largeur-align-avant-le-j-aime-6d1743d78e7c4cdd9d017ce05d562e75
Modification des class css
Et au passage, correction d'un mauvais retour à a ligne dans le texte du footer
> Réduction de largeur de colonne du post-content

- config/settings/dev.py
- lacommunaute/templates/forum_conversation/forum_attachments/attachments_detail.html
- lacommunaute/templates/forum_conversation/partials/post_feed.html
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_conversation/partials/posts_list.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/forum_member/subscription_topic_list.html
- lacommunaute/www/forum_views/tests_views.py
- lacommunaute/www/forum_views/views.py
🎸 Obtention de la permission `can_download_files`. Cette permission est gérée au niveau d'un `forum`, il est inutile de la demander pour chaque `attachment`. Cette permission est recupérée en une fois au niveau du template appelant le template `attachments_detail.html`
🎸 Gestion de la donnée `is_topic_head` d'un `post` dans le template `poster`, Cette donnée permet d'aiguiller vers la vue `topic_update` sinon vers la vue `post_update`. Le contexte du template appelant le template `poster.html` permet de déterminer la valeur attendue. Il permet d'éviter des requêtes dupliquées sur `post.is_topic_head`
🎸 Vue `ForumView`, modification du `prefetch_related`, reférence à `first_post` au lieu de `posts` puisque cette vue affiche seulement le premier `post`. Les `posts` suivant sont récupérés …
> Optimisation des requêtes de la vue d'un Forum (aka fil d'actualités d'une communauté)

- lacommunaute/www/forum_views/views.py
🎸 Selectionner les `forum` sans restriction de niveaux de profondeur pour afficher le nombre de `topic` et de `post` global au niveau du top-level `forum`. L'optimisation n'apporte aucun bénéfice et fausse le comptage des sujets et des réponses
top-level-forum : 0 sujet
la bande à itou : 2 sujets
cr rdv mensuel : 3 sujets
espace coconstruction : 6 sujets
Admin View
IndexView
ForumView
ForumView on subforum
> Compter les Sujets et les Réponses sans limite de profondeur dans les sous communautés

- lacommunaute/templates/forum/forum_form.html
- lacommunaute/templates/partials/header_nav_primary_items.html
- lacommunaute/www/forum_views/tests_views.py
- lacommunaute/www/forum_views/urls.py
- lacommunaute/www/forum_views/views.py
🎸 Créer un `forum` avec le `members_group` correspondant, le `group` des moderateurs et les droits associés :  
* anonyme
* authentifié
* membrer
* animateurs
🦺 la création des droits pourrait être optimisée
> Page de création de nouvelles communautés publiques avec les bonnes permissions

- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/partials/footer.html
- lacommunaute/templates/partials/header.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/A11Y-Am-lioration-des-title-et-aria-label-7e6d702c19e749b6bd4e18ff09937376
Amélioration de l'accessibilité. Remplacement de l'attibut `title` par `aria-label` sur balises de liens `<a>` .
De manière générale, il est maintenant recommandé d'utiliser `aria-label` plutot que `title` partout sauf sur les `<iframes>` (et les tooltip pour bs). Donc a mettre quand nécessaire sur les `<button>`, `<input>` (sans label), `<a>`
> Remplacement de l'attibut title sur balises de liens 

- lacommunaute/www/forum_views/tests_views.py
- lacommunaute/www/forum_views/views.py
🎸 Ajout de l'info `has_liked` et du nombre de `like` pour les `topic` de type `ANNONCE` dans le fil d'actualité d'un `forum`
🦺 les `topic` de type `annonce` sont collectés directement dans `get_context_data` et non via le queryset de la `ListView`
> Afficher les likes pour les annonces dans le fil d'actualités d'une communauté

- lacommunaute/templates/pages/home.html
🎸 Ajout de l'embed de l'enquète Tally sur la HP.
Carte notion: https://www.notion.so/plateforme-inclusion/Brancher-le-NPS-du-WP-sur-Django-501ce39fcc8e45e48e5bb2933fd551c0
Code dans le template
À priori, c'était à ne placer que sur la HP avec un affichage tous les 15 jours.
Cette temporalité n'est pas traitée dans cette PR, ça sera à faire dans un deuxième temps
>  Ajout de l'embed de l'enquète Tally "NPS" sur la HP

- lacommunaute/templates/forum/forum_list.html
- lacommunaute/templates/forum/partials/topics_and_members_counts.html
🎸 Dans les listes des `forum`, afficher le nombre de sujets et de réponses si le `forum` est de type `forum`
🎸 Dans les listes des `forum`, ne pas afficher le nombre de sujets et de réponses si le `forum` est de type `category` ou `link`
Liste des `forum`
Détail d'un `forum` avec un sous-forum de type `lien` et un sous-forum de type `forum`
> Correction de l'affichage du nombre de sujets et de réponses

- lacommunaute/forum/models.py
- lacommunaute/forum/tests.py
- lacommunaute/templates/forum/forum_list.html
- lacommunaute/templates/forum/partials/unanswered_topics_badge.html
- lacommunaute/www/forum_views/tests_views.py
- lacommunaute/www/forum_views/views.py
🎸 afficher le nombre de sujets non répondus dans la liste de `forum`
🎸 filtrer les `topic` non répondus de le fil d'actualités d'un `forum`
🦺 vérifier si la méthode `count_unanswered_topics` ne génère pas de requêtes en N+1
Liste des forums 
Fil d'actualités d'un forum
Topics non répondus d'un forum sans sous-forum
Topic non répondu d'un forum avec sous-forums
> Filtrer les questions sans réponses

- lacommunaute/templates/forum_conversation/partials/post_form.html
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- lacommunaute/templates/forum_conversation/post_update.html
- lacommunaute/templates/forum_conversation/topic_create.html
🎸 Suppression de la prévisualisation : pas de valeur ajoutée et source de bugs
🎸 Suppression du `nav-tab options` 
🎨 UI
Nouveau `Topic`
Nouveau `Topic` avec `Attachment`
Édition du `Topic`
Edition du `Post`
> Nettoyage des Formulaires de creation/mise à jour des Topic & Post

- lacommunaute/forum_stats/management/commands/collect_daily_matomo_stats.py
🎸 Mise en place de la management command pour automatiser la collecte des stats quotidiennes depuis matomo
🚧 technique
🦺 collecte les stats à partir du lendemain de la date de derniere collecte
🦺 collecte les stats jusqu'à la veille du traitement
🦺 management command appelée par une tâche cron
> Automatisation de la collecte des stats quotidiennes

- lacommunaute/templates/pages/home.html
cf titre
Le popup cesse de s'afficher pendant 14 jours à partir du moment où soit 
- l'utilisateur ferme manuellement le popup en cliquant sur la croix en haut à droite, soit 
- l'utilisateur soumet le formulaire. 
Tant que l'utilisateur n'a fait aucune de ces deux actions on continue d'afficher le popup.
La popup s'affiche au bout de 45 secondes (préférence du C2) mais ça peut être changé si vous préférez un affichage plus rapide (`const delayBeforeShowingPopupInSeconds = 45;`)
Pour annuler le masquage des 15 jours, il faut aller dans le localStorage de la console du navigateur et supprimer l'entrée "statsTallyPopupLastShown-mVGEr6"
> Montrer le popup Tally maximum une fois toutes les deux semaines

- clevercloud/collect_daily_matomo_stats.sh
- clevercloud/cron.json
🎸 automatiser la collecte des stats matomo via une `management command`, executée par une tâche `cron`
🎸 tâche executée tous les jours à 5h
🚧 technique
🦺 script sh de lancement de la management command dans le repertoire `clevercloud/`
🦺 cronjob standard paramétré dans le fichier `clevercloud/cron.json`
> CRON : mise en place de la collecte automatique des stats quotidiennes matomo

- lacommunaute/templates/forum_conversation/partials/topic_detail_actions.html
- lacommunaute/templates/forum_member/subscription_topic_list.html
- lacommunaute/www/forum_member_views/tests.py
- lacommunaute/www/forum_member_views/urls.py
- lacommunaute/www/forum_member_views/views.py
- lacommunaute/www/forum_views/tests_views.py
🎸 Suppression du code surchargé, lié aux fonctionnalités d'abonnement, pour éviter les confusions avec la gestion des notifications basées sur les Likes à venir
🚧 technique
> Abonnement - suppression du code mort

- lacommunaute/templates/event/event_calendar.html
- lacommunaute/www/event_views/tests.py
🎸 Afficher le bouton d'ajout d'évènement pour tous les visiteurs, y compris pour les visiteurs non authentifiés
🎸 Le clic sur le bouton pour les visiteurs non authentifiés renvoie vers IC
🎨 UX
> Afficher le bouton d'ajout d'évènement pour tous les visiteurs

- config/settings/base.py
- lacommunaute/notification/emails.py
- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_emails.py
- lacommunaute/notification/tests/tests_tasks.py
- lacommunaute/notification/tests/tests_utils.py
- lacommunaute/notification/utils.py
🎸 Remplacer l'envoi unitaire par un envoi groupé des nouveaux utilisateurs dans la séquence d'onboarding.
🎸 Correction des `attributes` pour valoriser les noms et prénoms
🚧 technique / performance
🦺 complément de la PR #195
> Notification : ajout *par lot* des nouveaux utilisateurs dans la sequence d'onboarding 

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
🎸 L'auteur d'un sujet est automatiquement ajouté à la liste des `likers` du `topic` pour envoyer des notifications sur l'activité de son sujet (ie reponses)
> Ajouter l'auteur d'un sujet dans la liste des "likers" du sujet

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
🎸 Ne pas ajouter l'utilisateur non authentifié qui poste un nouveau sujet, à la liste des likers de ce sujet
🪲 Correction de bug | PR #200
> FIX : Ne pas ajouter un poster non authentifié à la liste des likers d'un Sujet

- config/settings/base.py
- config/urls.py
- lacommunaute/templates/flatpages/default.html
- lacommunaute/templates/pages/landing_pages.html
- lacommunaute/templates/partials/header_nav_primary_items.html
- lacommunaute/www/pages/tests.py
- lacommunaute/www/pages/urls.py
- lacommunaute/www/pages/views.py
🎸 Permettre la création de landing pages depuis l'admin, sans redéploiement de code
🎸 Permettre aux utilisateurs `superuser` de visualiser la liste des landing pages existantes depuis leur `navbar`
🦺 Par défault, les landing utilisent le gabarit standard du site
🦺 Exploitation de l'app `flatpages` de Django
🦺 Les urls des `flatpages` ne sont pas prioritaires, elles sont déclarées en fin de liste des urls
Ecran d'admin de mise à jour d'une `flatpage`
Vue de la `flatpage` correspondante
Lien vers la liste des `flatpages` dans la `navbar`
Page de liste des `flatpages` actives sur le site
> Gérer les landing pages sur le site

- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/www/forum_conversation_views/tests.py
🎸 Harmoniser l'affichage avec les notifications emails
- Si le sujet ou la réponse est postée par un utilisateur authentifié : afficher son prénom + la premiere lettre de son nom (inchangé)
- Si le sujet ou la réponse est postée par un utilisateur NON authentifié : afficher le radical de son adresse email (la partie avant @) 
> Mise à jour de l'affichage du nom de l'auteur d'un post

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/templates/forum_conversation/partials/post_certified.html
- lacommunaute/templates/forum_conversation/partials/post_certified_badge.html
- lacommunaute/templates/forum_conversation/partials/topic_certified_post.html
- lacommunaute/www/forum_conversation_views/tests.py
- lacommunaute/www/forum_conversation_views/urls.py
- lacommunaute/www/forum_conversation_views/views.py
- lacommunaute/www/forum_views/tests_views.py
🎸 Afficher les 200 premiers caractères d'une réponse certifiée
🎸 Ajouter le lien "voir plus" pour déplier la réponse
🎸 Ajout de la vue HTMX `TopicCertifiedPostView` pour afficher le contenu de `topic.certified_post.post.content`
🦺 Vue HTMX
Fil d'actualités au chargement de la page
Réponse certifiée dépliée
Topic déplié (independant de la réponse certifiée)
> Ajout du lien "voir plus" sur les réponses certifiées

- clevercloud/collect_monthly_matomo_stats.sh
- clevercloud/cron.json
- lacommunaute/forum_stats/management/commands/collect_matomo_stats.py
🎸 Fixes de la PR #209 
* décaler la date de demarrage de collecte pour les périodes `week` et `month`
* ajustement des scripts et de la crontab
🚧 technique
> [Stats] automatiser la collecte des stats mensuelles (fixes)

- lacommunaute/forum/models.py
- lacommunaute/forum/tests.py
🎸 Utilisation d'une date avec timezone dans la méthode `forum.get_stats()` pour supprimer le warning.
🚧 technique
```
lacommunaute/forum/tests.py::ForumModelTest::test_get_stats
/home/vincentporte/Neuralia.co.Products/betagouv/itou-communaute-django/.venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1504: RuntimeWarning: DateTimeField Topic.created received a naive datetime (2023-03-09 00:00:00) while time zone support is active.
warnings.warn(
lacommunaute/forum/tests.py::ForumModelTest::test_get_stats
/home/vincentporte/Neuralia.co.Products/betagouv/itou-communaute-django/.venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1504: RuntimeWarning: DateTimeField Post.created received a naive datetime (2023-03-09 00:00:00) while time zone support is …
```
> FIX - suppression du warning lors de la recupération des stats d'un forum

- lacommunaute/forum/models.py
- lacommunaute/forum/tests.py
- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_models.py
- lacommunaute/templates/forum_conversation/partials/post_certified.html
- lacommunaute/templates/forum_conversation/partials/post_feed.html
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_conversation/partials/posts_list.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/pages/home.html
- lacommunaute/www/forum_views/tests_views.py
- lacommunaute/www/forum_views/views.py
🎸 Afficher les questions posées dans les `forum` public, qui n'ont reçues aucune reponse, dans un onglet de la page d'accueil
🎸 Premier cas où des `topic` sont affichés sans qu'aucun `forum` ne soit défini en contexte
🦺 modification de templates pour gérer les cas (`poster` et `download_permission`) où aucun `forum` n'est passé en contexte
🦺 ajout de `manager` pour obtenir les `topic` non répondus des `forum` public
🦺 ajout d'une `tablist` dans `IndexView`, selon la présence du paramètre `new` dans l'url, l'onglet des questions en attente de réponse est mise en avant à la place de celui de la liste des `forum`
IndexView, paramètre `new` absent de l'url
IndexView avec le paramètre `new` dans l'url
> Afficher les questions en attentes de réponse

- lacommunaute/www/forum_views/tests_views.py
- lacommunaute/www/forum_views/views.py
🎸 Ajout du contexte pour afficher les `like`, les `attachments` et les `votes` sans surcharger la DB
🚧 technique
🦺 factoriser les annotations, les select_related et les prefetch_related
> FIX: ajout du contexte des questions en attente sur la homepage

- lacommunaute/forum_stats/management/commands/compute_answering_delay.py
🎸 calculer les délais de réponses sur un mois des questions répondues dans les `forum` public
🦺 assumed untested
> STATS  : calculer les délais de réponses sur un mois

- lacommunaute/forum_stats/management/commands/compute_answering_delay.py
🎸calculer le taux de réponses inférieures à 48h sur un mois des questions répondues dans les forum public
suite #216 
🦺 assumed untested
> STATS  : calculer le taux de réponses inféreures à 48h sur le mois

- lacommunaute/templates/pages/home.html
🎸 Ajout d'un tag matomo sur la liste des questions en attente
🚧 technique
> Ajout d'un tag matomo sur la liste des questions en attente

- lacommunaute/templates/forum_conversation/partials/post_feed.html
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/www/forum_views/tests_views.py
- lacommunaute/www/forum_views/views.py
🎸 Le lien `éditer` dans le fil d'actualités de la vue `ForumView` déclenche des requêtes en base pour vérifier si l'utilisateur peut éditer un `Post` et ceux pour chaque `Post`. Pour limiter le nombre de requêtes, et optimiser l'affichage de la page, le lien `éditer` est affiché uniquement dans la vue `TopicView` et lors de l'ajout d'un `post` depuis le fil d'actualités (`PostFeedCreateView`)
🎸 Amélioration des requêtes de `ForumView`
🚧 technique
Fil d'actualités sans lien "éditer"
Vue de détail du `topic` avec les liens "éditer"
Ajout d'un `post` depuis le fil d'actualités, avec le lien "éditer"
> Optimisation du fil d'actualités d'une communauté

- lacommunaute/templates/forum_conversation/partials/post_certified.html
- lacommunaute/templates/forum_conversation/partials/post_feed.html
- lacommunaute/templates/forum_conversation/partials/posts_list.html
- lacommunaute/templates/forum_conversation/partials/topic_certified_post.html
- lacommunaute/templates/forum_conversation/partials/topic_content.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/utils/templatetags/str_filters.py
- lacommunaute/utils/tests.py
- lacommunaute/utils/urls.py
- lacommunaute/www/forum_views/tests_views.py
🎸 L `urlizer` générait un conflit avec le rendu des liens et des images en markdown.
🎸 Surcharge de l `urlizer` pour ignorer les liens déjà intégrés dans des tags html
🎸 Uniformisation des templates de rendus de `post` et de `topic` : ajout de `img-fluid`, et remplace de `truncatechars` par `truncatechars_html`
🚧 technique
après "voir plus"
version edition du message en MD
> [FIX] rendre le markdown et les url cliquables compatibles

- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/pages/home.html
🎸 ajout de la classe `topiclist` dans le `tab-content` de la page d'accueil pour afficher l'avatar en thumbnail dans la liste des questions en attente
> [fix] affichage de l'avatar dans la liste des questions en attente

- lacommunaute/templates/pages/home.html
- lacommunaute/www/forum_conversation_views/tests.py
- lacommunaute/www/forum_conversation_views/urls.py
- lacommunaute/www/forum_conversation_views/views.py
- lacommunaute/www/forum_views/tests_views.py
🎸 Afficher la liste des dernières réponses certifiées dans un onglet dedié de la page d'accueil de la communauté
🎸 Précharger cette liste avec le tag `hx-trigger="load"` pour réduire le délai d'affichage lors du clic sur l'onglet sans ralentir le chargement de la page d'accueil
🦺 Les réponses certifiées étant liées à des `forum` public, tous les utilisateurs (même non loggés) peuvent contribuer. La gestion des droits n'est pas implémentée (perf)
> Liste des dernières réponses certifiées

- lacommunaute/forum_conversation/forms.py
- lacommunaute/forum_conversation/tests/tests_forms.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- lacommunaute/templates/partials/form_field.html
🎸 Permettre la sélection d'un ou plusieurs tags lors de la création et de la mise à jour d'un `topic`
🎸 Gestion des `checkboxselectmultiple`
🦺 surcharge de la classe `TopicForm` de `machina` : ajout du `ModelMultipleChoiceField`, enrichissement de la méthode `save` et initialisation des `tags` déjà sélectionnés en mise à jour
🦺 suite de la PR #225 
Nouveau Topic
Topic après enregistrement
Mise à jour du Topic
Topic après mise à jour
> [TAGS] etape 1 - ajout des Tags lors de la creation/mise à jour d'un Topics

- clevercloud/cron.json
🎸 Mise à jour de la tâche `cron` pour envoie d'une notification de `topic` en attente de réponse, à un sous-ensemble des experts volontaires chaque jour
🚧 technique
> [Notification] sujets non réponds, planification quotidienne des experts volontaires

- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
🎸 prefetch des objets `tags` dans la méthode `optimized_for_topics_list` 
🎸 amélioration de tests sur les `tags`
🚧 technique
> 261 prefetch tags dans optimized for topics list

- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_tasks.py
🎸 Ne pas envoyer de notification si aucune question en attente de réponse
🦺 Décision d'architecture
> [FIX] Ne pas envoyer de notification si aucune question en attente

- lacommunaute/static/stylesheets/itou_communaute.scss
- lacommunaute/templates/forum/forum_list.html
- lacommunaute/templates/forum/partials/topics_and_members_counts.html
🎸 Correction de l’erreur de pluriel dans le compteur de sujets et de messages
https://www.notion.so/plateforme-inclusion/0-sujets-0-messages-1-sujets-1-messages-d79cf8d80b244be5bcf9db20b2b27688?pvs=4
Au passage, fix de la hauteur du dropdown-menu du sous menu de header
> Correction de l’erreur de pluriel dans le compteur de sujets et de messages

- config/settings/base.py
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/views.py
- lacommunaute/inclusion_connect/views.py
- lacommunaute/templates/partials/ask_a_question.html
- lacommunaute/templates/partials/header_nav_secondary_items.html
- lacommunaute/utils/middleware.py
- lacommunaute/utils/tests.py
🎸 Dynamiser le chargement des `forum` visibles dans `request.session[UPPER_VISIBLE_FORUMS]` en les mettant à jour avec la liste des `forum` collectés dans `IndexView`
🎸 Supprimer le chargement de `request.session[UPPER_VISIBLE_FORUMS]` lors de l'authentification `inclusion_connect` car inutile
🚧 technique
🦺 `VisibleForumsMiddleware.process_request` n'est utile que lors d'un accès direct à `TopicView` (par exemple), sans naviguer via `IndexView`
🦺 `request.session[UPPER_VISIBLE_FORUMS]` est exploité dans les templates `header_nav_secondary_items` et dans `ask_a_question`
> Homepage - call to actions - dynamiser le chargement de la liste des communautes

- lacommunaute/templates/forum_conversation/topic_create.html
- lacommunaute/templates/pages/home.html
- lacommunaute/templates/partials/ask_a_question.html
- lacommunaute/templates/partials/banner.html
- lacommunaute/templates/partials/footer.html
🎸 Ajout d'une bannière pour rediriger les demandes de support du site des emplois au bon endroit
🎨 UX
> Bannière pour la redirection vers le support des emplois

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/urls.py
- lacommunaute/forum/views.py
- lacommunaute/forum_conversation/enums.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_conversation/urls.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/forum_conversation/views_htmx.py
- lacommunaute/inclusion_connect/tests/tests_views.py
- lacommunaute/inclusion_connect/views.py
- lacommunaute/pages/tests/tests.py
- lacommunaute/templates/404.html
- lacommunaute/templates/forum_conversation/partials/topic_filter.html
- lacommunaute/templates/forum_conversation/partials/topic_tags.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/pages/home.html
- lacommunaute/templates/partials/header.html
- lacommunaute/templates/partials/header_nav_secondary_items.html
- lacommunaute/utils/templatetags/url_add_query.py
- lacommunaute/utils/tests.py
🎸 Simplification de la page d'accueil en réduisant le nombre d'onglets visibles et en valorisant les questions/réponses les plus récentes
🎸 Ajout de filtres dans l'onglet questions/réponses
🎸 Gestion du filtre lors du chargement des sujets suivants dans l'onglet questions/réponses
🎸 Suppression des onglets 'questions en attente' et 'réponses certifiées'
🥁 Changement de rupture (modification ou caractéristique qui empêcherait une fonctionnalité existante de fonctionner comme prévu)
🦺 réutilisation du tag `url_add_query` en provenance des emplois pour concaténer les paramètres dans les `querry` : filter + page
🦺 fusion de `IndexView` et `TopicListView`, gestion du template selon le contexte htmx
🦺 `TopicNewsListView` rendue independante de `TopicListView` pour du code plus léger
Page …
> Liste des Questions/Réponses avec filtres sur la page d'accueil

- lacommunaute/event/tests/tests_views.py
🎸 correction de la date dans le test de la liste des evenements pour éviter les erreurs de timezone
🚧 technique
> [FIX] correction de la date dans le test de la liste des evenements

- lacommunaute/utils/matomo.py
- lacommunaute/utils/tests.py
🎸 Filtrer les evenements Matomo sur le `label` `engagement` depuis la mise en place du suivi du lien de support des emplois
🚧 technique
> [FIX] stats quotidiennes

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/utils/middleware.py
- lacommunaute/utils/tests.py
🎸 ne pas afficher les `forum` de type `FORUM_CAT` dans la liste des forums visibles pour éviter le rattachement de `topic` à ce type de `forum`
> FIX : ne pas afficher les forums de type catégorie dans la liste des forums visibles

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
🎸 Ne pas afficher les questions non répondues des thématiques privées
> Limiter l'affichage des questions non répondues aux thématiques publiques

- lacommunaute/pages/sitemaps.py
- lacommunaute/pages/tests/test_sitemap.py
🎸 Remplacer le `last_post_on` par `update` de l'instance `forum` pour alimenter `<lastmod>` du fichier `sitemap`.
`last_post_on` peut être vide pour les forums de type catégorie, lien ou ceux dont la description sert de fiche technique/FAQ
🚧 technique
> [FIX] date de modification des Forum dans le fichier sitemap

- clevercloud/python.json
- config/settings/base.py
> [SEARCH] correction du endpoint S3 pour le stockage de l'index

- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_tasks.py
🎸 Limiter l'appel à l'API d'onboarding (sendinblue/brevo) uniquement si de nouveaux utilisateurs se sont enregistrés depuis le dernier enregistrement `EmailSentTrack`
🚧 technique
> [NOTIFICATION] appel à l'api d'onboarding

- lacommunaute/forum_member/tests/tests_view.py
- lacommunaute/forum_member/urls.py
- lacommunaute/forum_member/views.py
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_member/moderator_profiles.html
- lacommunaute/templates/forum_member/profiles.html
- lacommunaute/templates/partials/header_nav_primary_items.html
🎸 remplacer le `pk` par le `username` dans l'url de `ForumProfileDetailView` pour empecher le scrapping itératif
🚧 technique
🦺 `username` provient d'inclusion connect
🦺 ajout d'un `select_related` sur `ModeratorProfileListView`
Utile pour les changements liés à l'UI.
> [FORUM_MEMBER] sécuriser l'accès aux profils

- lacommunaute/forum_stats/management/commands/export_counts.py
🎸 `management command` pour exporter les données datées de connection, publication, like et upvote, consolidées par adresse email
> [STATS] exporter l'activité du site pour entrainer le modèle de clustering non supervisé

- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_tasks.py
🎸 correction du parametre `filter` dans l'url transmise dans les emails de notifications de questions en attente
> [NOTIFICATION] filtre sur les questions non répondues

- lacommunaute/pages/tests/test_homepage.py
- lacommunaute/pages/views.py
🎸 trier les dernières questions par date de création et non plus sur `last_post_on` (date du dernier `Post`)
> [HOME] tri des dernières questions

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
🎸 Trier les actualités par ordre de `last_post_on` descendant dans `NewsFeedTopicListView`
> [FIX] tri des actualités

- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/shortcuts.py
- lacommunaute/forum_conversation/tests/tests_shortcuts.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_upvote/admin.py
- lacommunaute/forum_upvote/migrations/0004_convert_to_genericforeignkey.py
- lacommunaute/forum_upvote/models.py
- lacommunaute/forum_upvote/tests/tests_models.py
- lacommunaute/forum_upvote/tests/tests_views.py
- lacommunaute/forum_upvote/views.py
🎸 Remplacer la clé étrangère `Post` dans le modèle `UpVote` par une `GenericForeignKey` pour préparer l'upvote d'autres objets de la communauté (ie les `Forum`)
🚧 technique, fait suite à la PR #356 
🦺 dans le modele `UpVote`, transformer la `ForeignKey` vers `Post` en `GenericForeignKey`
🦺 migrer les données aller-retour
🦺 adapter les appels à `UpVoteFactory` et les `UpVote.objects.filter()` existants
🦺 ajout d'une `GenericRelation` du modele `Post` vers le modèle `UpVote`
> [UPVOTE] convertir la clé étrangère Post en clé étrangère générique

- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_tasks.py
> [NOTIFICATION] correction de l'url d'accès aux questions non répondues dans l'email de notification

- config/urls.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_moderation/tests/test_topic_delete_view.py
- lacommunaute/forum_moderation/urls.py
- lacommunaute/forum_moderation/views.py
- lacommunaute/templates/forum_conversation/partials/topic_detail_actions.html
🎸 surcharge de la vue `TopicDeleteView` de `django-machina` pour résoudre l'erreur de `reverse` dans la méthode `get_success_url`
🚧 technique
> [MODERATION] mise à jour de la vue de suppression d'un `Topic`

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/templates/event/event_calendar.html
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum_conversation/partials/topic_likes.html
- lacommunaute/templates/forum_member/join_forum_landing.html
- lacommunaute/templates/partials/ask_a_question.html
- lacommunaute/templates/partials/header_nav_primary_items.html
- lacommunaute/templates/partials/upvotes.html
🎸 AJouter la balise `rel=nofollow` sur les pages à faible valeur ajoutée :
- liens d'authentification via IC
- liens "poser une question"
- lien "répondre"
🚧 technique
🦺 SEO
> [SEO] ajout de balises nofollow

- lacommunaute/forum_conversation/factories.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
🎸 Permettre le filtre des `topics` sur les `tags` dans `TopicListView`
🎸 Gérer les combinaisons de filtrage 'tags' x 'filter'
🚧 technique
🦺 l'UI sera adaptée dans la PR - partie 2
> [TOPICS] filtrer les sujets à partir des étiquettes - part 1

- .gitignore
- lacommunaute/forum_search/tests/test_search_indexes.py
🎸 Résoudre l'erreur aléatoire, lors de l'execution des tests en mode distribué :
```
whoosh.index.EmptyIndexError: Index 'MAIN' does not exist in FileStorage('/path/to/betagouv/itou-communaute-django/whoosh_index')
```
Les tests en mode distribué provoquent parfois la suppression de l'index de recherche "commun". La solution consiste à créer un index par worker. Chaque worker crée et supprime son index indépendamment des autres.
🚧 technique
🦺 la fixture `worker_id` récupère l'id du worker, sinon `master` en mode non distribué
🦺 mise à jour du `.gitignore` ;)
> [SEARCH] fix - le fichier d'index est absent lors de certains tests

- CHANGELOG.md
- poetry.lock
- requirements/base.txt
- requirements/dev.txt
- [PAGES] mise à jour des pages de mentions  (#397)
- [RECHERCHE] fix - le fichier d'index est absent lors de certains tests (#394)
- [RECHERCHE] barre de recherche dans le header (#391)
- [STATISTIQUES] août 2023 (#390)
- [SEO] ajout de balises nofollow (#387)
- [SEO] suppression de l'aide MD (#385)
- [TOPICS] filtrer les sujets à partir des étiquettes - part 1 (#384)
- [DOCUMENTATION] titre des liens vers les autres fiches du thème (#378)
- [DOCUMENTATION] déposer des images publiques (#388)
- [MODERATION] mise à jour de la vue de suppression d'un `Topic` (#371)
- [NOTIFICATION] correction de l'url d'accès aux questions non répondues dans l'email de notification (#370)
- [SETTINGS] ajout de la compression des données (#380)
- [SETTINGS] peupler les recettes jetables automatiquement …
> Changelog V2.1

- lacommunaute/forum_conversation/factories.py
- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_models.py
- lacommunaute/notification/emails.py
- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_emails.py
- lacommunaute/notification/tests/tests_tasks.py
- lacommunaute/notification/tests/tests_utils.py
- lacommunaute/notification/utils.py
🎸 Notifier toutes les parties prenantes d'un `Topic` lors des nouveaux messages.
🎸 Les parties prenantes sont les `posters` anonymes et authentifiés, les `likers` et les `upvoters`.
🎸 Le `poster` du dernier `post` du `topic` n'est pas notifiés.
🎸 Deux types de notifications :
1. notification de la première réponse, envoyée dans l'heure
2. notification des réponses suivantes, envoyées quotidiennement
🎢 Evolution de la fonctionnalité (changement non cassant).
🦺 L'objet `EmailSentTrack` permet d'enregistrer la date du dernier traitement de notification. Ne sont considérés que les `Topic` mis à jour après. 
🦺 notifications de premiere reponse (tache cron hourly)
* méthode `lacommunaute.notification.utils.collect_first_replies`
* `EmailSentTrack`, kind : `EmailSentTrackKind.FIRST_REPLY` 
🦺 …
> [NOTIFICATION] informer les parties prenantes des nouvelles réponses

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum_conversation/partials/post_feed_form_collapsable.html
- lacommunaute/templates/forum_conversation/topic_detail.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/forum_conversation/topic_list_newsfeed.html
- lacommunaute/templates/partials/form_field.html
- lacommunaute/templates/partials/form_field_mentions.html
- lacommunaute/templates/partials/social_share_buttons.html
🎸 Supprimer les ID en doublons dans les templates `social_share_buttons` et `form_field_mentions`. Ces templates sont inclus pour chaque sujet dans les listes de `topic`
🚧 technique
🦺 l'ID du `Topic` dans `form_field_mentions` est initié par le template `post_feed_form_collapsable`, et transmis via le template `form_field`
> [SEO] dédoublonner les ID

- lacommunaute/event/tests/tests_views.py
- lacommunaute/event/views.py
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/inclusion_connect/tests/tests_views.py
- lacommunaute/inclusion_connect/views.py
- lacommunaute/templates/event/event_calendar.html
- lacommunaute/utils/templatetags/str_filters.py
- lacommunaute/utils/tests.py
🎸 aligner le `redirect_field_name` utilisé dans l'app `inclusion_connect` avec celui de l'authentification django pour rediriger correctement l'utilisateur lors de sa tentative d'accès à une vue requierant son authentification
🚧 technique
🦺 ne s'applique pas aux vues HTMX requierant authentification (à traiter dans un temps ultérieur)
> [LOGIN IC] gérer les redirections après authentification

- lacommunaute/templates/forum_conversation/forum_attachments/attachments_detail.html
- lacommunaute/utils/templatetags/attachments_tags.py
- lacommunaute/utils/tests.py
🎸 afficher l'icone `damage file` et le nom du fichier si le fichier n'est pas trouvé dans le repertoire de stockage, au lieu de faire planter le template
🚧 technique
🦺 Cas fréquent lors du restore de la DB en local, sans les fichiers associés
🦺 Pourrait se produire en prod en cas d'effacement de tout ou partie du S3
Fichier présent
Fichier absent
> [CONVERSATION] gérer les fichiers manquants

- lacommunaute/templates/forum_conversation/partials/posts_list.html
- lacommunaute/templates/forum_conversation/partials/topic_detail_actions.html
- lacommunaute/templates/forum_conversation/topic_list.html
🎸 nettoyage des scripts : 
1. suppression du code mort : `onclick=DisabledMe` en prévision de l'application des Content Security Policies
2. insertion unique du script d'ajout de la classe `d-none` au bouton en objet au niveau du template `topic_list.html` au lieu de `posts_list.html` pour éviter la duplication du code dans la page rendu ET une erreur dans la vue de détail d'un `topic`
🚧 technique
> [CONVERSATION] masquer le bouton "voir les 999 reponses" (fix)

- config/settings/base.py
- lacommunaute/templates/forum_conversation/partials/topic_likes.html
- lacommunaute/templates/layouts/base.html
- lacommunaute/templates/pages/home.html
- lacommunaute/templates/pages/statistiques.html
- poetry.lock
- pyproject.toml
- requirements/base.txt
- requirements/dev.txt
🎸 Paramétrage des `Content Security Policies` et `Permission Policies`
🛸 Installation de `django-csp` et de `django-permissions-policy`
🚧 `htmx view` appelée par une `class based view` Django 
surcharge du middleware pour avoir la même valeur de `request.csp_nonce` dans les 2 templates rendus (vérifier l'utilité)
🚧 technique
🦺 suppression de `onclick=DisabledMe` dans l'appel HTMX & correction du placement du script pour masquer le bouton `voir les 99 réponses`
> Content Security Policies / Permission Policies

- CHANGELOG.md
- poetry.lock
- requirements/base.txt
- requirements/dev.txt
- [STATS] un entonnoir adaptatif (#418)
- [CONVERSATION] masquer le bouton "voir les 999 reponses" (fix) (#417)
- [CONVERSATION] gérer les fichiers manquants (#411, #410, #409)
- [SEO] dédoublonner les ID (#408)
- [INCLUSION CONNECT] gérer les redirections après authentification (#413)
- [NOTIFICATION] mise à jour de la planification de `send_notifs_when_following_replies.sh` (#403)
- Nettoyage des dépendances de developpement (#416)
- HTMX - mise à jour - version 1.9.5 (#415)
- mise à jour des dependances (#405)
> Changelog v2.2

- config/settings/base.py
🦺 autoriser explicitement `https://stats.data.gouv.fr/piwik.js` pour réactiver les stats matomo
🦺 limiter l'autorisation de `https://cdn.jsdelivr.net` à `https://cdn.jsdelivr.net/npm/chart.js`
🚧 technique
> Content Security Policies - patch

- .github/workflows/review-app-creation.yml
- config/settings/base.py
- config/settings/dev.py
- lacommunaute/templates/layouts/base.html
- lacommunaute/utils/matomo.py
- lacommunaute/utils/settings_context_processors.py
- lacommunaute/utils/tests.py
🎸 rétablir l'envoi des stats d'activités vers matomo : correction des CSP
🎸 rendre paramétrables (url et token) l'envoi des stats vers l'instance matomo choisie
🪲 Correction de bug
🚧 technique
🦺 mise à jour de la gestion du token d'authentification dans `get_matomo_data`
🦺 ajouter `MATOMO_SITE_ID`, `MATOMO_BASE_URL` et `MATOMO_AUTH_TOKEN` dans les variables d'env clevercloud
🦺 Suppression de la variable `COMMU_ENVIRONMENT` devenue inutile
>  Content Security Policies - patch 4 - matomo stats

- lacommunaute/forum/tests/tests_views.py
🎸 [`test_numqueries`](https://github.com/betagouv/itou-communaute-django/blob/866cc91e30261b48d72b538ae8766f488a88bb19/lacommunaute/forum/tests/tests_views.py#L229) dénombre les requêtes de la vue `ForumView`. Selon le type de lancement (unitaire ou dans la suite de test), le chargement du `Content_Type` est inclus dénombré ou pas dans ce test.
🎸 Solution : vider le cache systématiquement lors du lancement de ce test, pour rendre le dénombrement reproductible.
🚧 technique
🦺 Pourrait concerné les autres vues liées à l'utilisation de `Upvote`. À traiter au cas par cas.
> [TECH] fiabilisation d'un test

- lacommunaute/event/tests/tests_views.py
- lacommunaute/event/views.py
- lacommunaute/templates/event/event_archive_month.html
🎸 afficher le message "aucun évènement" au lieu d'une `404` pour un mois sans evènement.
🎸 ajouter un `title` à la vue `EventMonthArchiveView`
🚧 technique
> [Evenement] patch #1

- .env.template
- lacommunaute/inclusion_connect/tests/tests_views.py
- lacommunaute/inclusion_connect/views.py
🎸 mise à jour du mécanisme de déconnection
🚧 technique
> [INCLUSION CONNECT] adapter l'authentification à la nouvelle version d'IC

- lacommunaute/templates/forum_search/search.html
🎸 affichage d'un formulaire de NPS allégé lorsque la recherche obtient des résultats.
🦺 Affichage inconditionnel
🦺 formulaire `3xDBMv`
avec résultats
sans résultat
> [NPS] sous les résultats de rechercge

- Makefile
- lacommunaute/forum/factories.py
- lacommunaute/forum_conversation/factories.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/metabase/tests/test_extract_tables_command.py
- lacommunaute/utils/tests.py
🦺 Mise à jour du `Makefile`
🦺 Mise à jour des tests en regard des `deprecation warning` 
* factory boy : `Factory._after_postgeneration will stop saving the instance after postgeneration hooks in the next major release`
* file storage : `django.core.files.storage.get_storage_class is deprecated in favor of using django.core.files.storage.storages`
* assertion : `assertQuerySetEqual`
🚧 technique
> Mise à jour des lignes de code dépréciées dans le futur + makefile

- .pre-commit-config.yaml
- Makefile
- lacommunaute/templates/forum_conversation/forum_polls/poll_preview.html
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/layouts/base.html
- lacommunaute/templates/pages/contact.html
- poetry.lock
- pyproject.toml
- requirements/base.txt
- requirements/dev.txt
🎸 remettre en place `djhtml` dans `pre-commit` et la CI. `djlint` ne gere pas correctement (par défaut) les `tags` dans les blocs de scripts.
🚧 technique
> [LINTERS] suppression djlint au profit de djhtml

- lacommunaute/templates/forum_conversation/partials/poster_light.html
- lacommunaute/templates/pages/home.html
#481 
Afficher la date de mise à jour pour les fiches techniques (au lieu de la date de creation)
> [HOME] afficher les dates/heures sur la page d'accueil (fix)

- docker-compose.yml
Éviter d’exposer la base de données au public pendant le développement
La machine de dev était configurée pour écouter les demandes sur le réseau. Lors du développement dans un environnement partagé (café, train, coworking), d’autres personnes du réseau peuvent se connecter à la base de données (en l’absence de parefeu ou s’il est mal configuré), et éventuellement récupérer son contenu, s’ils devinent le mot de passe utilisé dans l’environnement de développement.
🚧 technique
> Éviter d’exposer la base de données au public pendant le développement

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
Amélioration du filtrage par tag, en ignorant les majuscules.
Correction d’un test qui échouait de manière intermittente.
🪲 Correction de bug
🚧 technique
> Permettre de filtrer les sujets avec des tags en majuscule

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- Makefile
- lacommunaute/templates/forum_conversation/forum_polls/poll_preview.html
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/layouts/base.html
- lacommunaute/templates/pages/contact.html
- lacommunaute/templates/pages/statistiques.html
- poetry.lock
- pyproject.toml
- requirements/base.txt
- requirements/dev.txt
Le contenu des balises `<script>` étaient reformattées par djlint suivant la syntaxe htmldjango. Évidemment, le résultat n’était pas beau à voir.
Exclure les scripts inline avec `{# djlint: off #}` permet d’éviter le reformattage. djlint semble avoir un souci pour préserver l’indentation à la suite du commentaire `{# djlint: on #}`, peut-être https://github.com/djlint/djLint/issues/703 ?
> Remettre en place djlint

- lacommunaute/templates/pages/home.html
- lacommunaute/templates/partials/ask_a_question.html
🎸 AB test - Fréquentation de la page documentation selon l'installation d'un bouton spécifique sur la homepage.
Version Originale
Variation Ajout d'un bouton plein
Variation Ajout d'un bouton outlined
🎨 UI
🦺 Ajout d'un script matomo dans `home.html`
🦺 La bascule d'UI est gérée via le param `btn` dans l'url
> [HOMEPAGE] AB test fréquentation de la page documentation

- config/settings/base.py
`True` est la valeur par défault, et le setting sera supprimé dans Django 5.0.
🚧 technique
> Retirer le setting USE_L10N

- lacommunaute/templates/partials/header_nav_secondary_items.html
🎸 Remplacer le lien vers le calendrier par le lien vers le site de l'évènement `inclusion-demain` dans le header
🎨 UI
> [HOMEPAGE] mettre en avant l'evenement inclusion-demain

- lacommunaute/forum_search/tests/__snapshots__/test_search_indexes.ambr
- lacommunaute/forum_search/tests/test_search_indexes.py
- lacommunaute/forum_search/views.py
- lacommunaute/templates/forum_search/search.html
- lacommunaute/templates/forum_search/search_form.html
- lacommunaute/utils/testing.py
- lacommunaute/utils/tests.py
- poetry.lock
- pyproject.toml
- requirements/base.txt
- requirements/dev.txt
🎸 Ajouter le bouton "poser la question" sur la page de résultat
🎸 Suppression du formulaire embarqué Tally en bas de page
🎸 Correction de l'espacement entre les `radiobutton` du formulaire
🦺 Ajout de `forum` en contexte de la vue `FacetedSearchView` pour hydrater le retournement de l'hyperlien `topic:create`
🦺 Ajout de 2 snapshots dans `test_search_indexes.test_extra_context` : formulaire avant recherche, recherche sans résultat.
🦺 Installation de `beautifulsoup4`, `sirupy` et `html5lib` pour gérer les snapshots et parser le contenu html de la balise `main`
🦺 AJout de la méthode `parse_response_to_soup` et de son test : reprise des emplois, [PR#3525](https://github.com/gip-inclusion/les-emplois/pull/3525) …
> [RECHERCHE] suggerer de poser la question si les résultats ne conviennent pas

- config/settings/_sentry.py
🎸 Activer https://docs.sentry.io/product/performance/.
> Permettre d’activer le suivi de perfs Sentry

- docker-compose.yml
- docker/django/Dockerfile
- docker/django/entrypoint.sh
Ne pas installer les dépendances Python en tant que `root`.
Copier les emplois.
Utiliser la façon documentée d’installer PostgreSQL.
🚧 technique
> MàJ de la recette pour construire l’image django

- lacommunaute/templates/partials/promotion_banner.html
🎸 Remplacer la banniere d'inscription  à inclusion-demain par la bannière "les 2 font la paire"
🎨 UI
> Reactivation de la bannière les 2 font la paires

- poetry.lock
- pyproject.toml
Python 3.11 est la version utilisée sur Clever.
> Python 3.11 dans les dépendances Poetry

- lacommunaute/templates/partials/social_share_buttons.html
> Retirer noqa: T027 des options de partage

- lacommunaute/templates/layouts/base.html
En cas de conflits, les thèmes définis par l’équipe devraient avoir la précédence.
🚧 technique
Refs #526
> Préférer les styles itou à machina.board_theme

- lacommunaute/pages/tests/tests.py
- lacommunaute/pages/views.py
🎸 Supprimer la limite de 3 mois sur l'extraction des stats d'impact mensuelles
🎨 UI
> [STATS] impact sans limite de durée

- lacommunaute/templates/pages/home.html
- lacommunaute/templates/partials/ask_a_question.html
🎸 L'AB Test a revelé que l'ajout d'un bouton vers la documentation augmente significativement le taux de conversion de la page. La version 'outlined' obtient des résultats légèrement meilleurs que le bouton plein. Le bouton `outlined` est mis en place.
🎨 UI
> [HOMEPAGE] fin AB Test, ajout bouton outlined vers la documentation

- lacommunaute/templates/forum_conversation/topic_create.html
- lacommunaute/templates/forum_moderation/moderation_queue/list.html
- lacommunaute/templates/pages/home.html
- lacommunaute/templates/partials/anonymous_banner.html
- lacommunaute/templates/partials/header_nav_primary_items.html
🎸 ajout d'un lien dans le menu superuser pour accéder à la liste des sujets à moderer
🎸 ajout de bandeau d'infos pour inciter les utilisateurs à se connecter
🎸 paramétrage manuel : les utilisateurs anonymes ne peuvent plus poster sans modération
⚠️ hotfix
🚧 technique
> [MODERATION] activation de la moderation queue

- .github/workflows/ci.yml
- config/settings/base.py
🎸 Django-compressor se plaignait de ne pas trouver certains _template tags_ et variables. En réalité, quelques éléments manquaient pour réaliser la compression hors-ligne avec `./manage.py compress`.
🚧 technique
Fixes #526
> Correction des erreurs de django-compressor au déploiement

- lacommunaute/templates/forum_conversation/topic_list.html
🎸 Ajout d'un lien vers le `forum` du `topic` lorsque le `forum` est différent de celui en contexte.
🦺 `TopicList` broadcast un objet `forum` dans son contexte, soit le `forum` associé à la vue quand l'url est du type `/forum/slug-pk/`, soit le premier forum public quand l'url est `/topics/`
> [TOPIC] ajout d'un lien vers le forum

- lacommunaute/surveys/admin.py
- lacommunaute/surveys/apps.py
- lacommunaute/surveys/enums.py
- lacommunaute/surveys/factories.py
- lacommunaute/surveys/forms.py
- lacommunaute/surveys/migrations/0001_initial.py
- lacommunaute/surveys/migrations/0002_recommendation_alter_dsp_availability_and_more.py
- lacommunaute/surveys/models.py
- lacommunaute/surveys/recommendations.py
- lacommunaute/surveys/recommendations.toml
- lacommunaute/surveys/tests/test_views.py
- lacommunaute/surveys/views.py
- lacommunaute/templates/partials/header_nav_secondary_items.html
- lacommunaute/templates/surveys/dsp_detail.html
- lacommunaute/templates/surveys/dsp_form.html
- lacommunaute/users/factories.py
Recommander des actions suite au diagnostic parcours IAE. Pour le moment, simplissime : une réponse correspond à une recommendations.
Gestion des accès avec la permission `surveys.add_dsp`
Closes #511
> Recommandations

- config/settings/base.py
- lacommunaute/pages/tests/test_homepage.py
🎸 Le titre du site n’affiche plus Accueil- Machina mais Accueil- La communauté de l'inclusion.
Problème introduit dans f81390f4bef63f4c2896180fcf25fabbb2302733.
> Corriger le <title> du site

- lacommunaute/forum_moderation/tests/test_post_disapprove_view.py
- lacommunaute/forum_moderation/views.py
🎸 Lors de la desapprobation d'un `post`, l'email de l'utilisateur anonyme est ajouté dans `BouncedEmail`. 
🎸 `BouncedEmail` contient une contrainte d'unicité sur l'email.
🎸 Correction de la surcharge de la vue `PostDisapproveView`
🚧 technique
> [MODERATION] desapprobation d'un post avec email dejà bounced

- lacommunaute/forum_member/models.py
- lacommunaute/forum_member/tests/tests_models.py
- lacommunaute/forum_member/tests/tests_view.py
- lacommunaute/forum_member/urls.py
- lacommunaute/forum_member/views.py
- lacommunaute/templates/forum_member/forum_profile_detail.html
- lacommunaute/templates/forum_member/profiles.html
- lacommunaute/templates/partials/footer.html
🎸 Afficher les `forum_profile` qui ont posté au moins 3 `post` sur les 3 derniers jours dans une page type `leaderboard`
🎸 Les `posts` anonymes ne sont pas pris en compte.
🦺 Réutilisation du gabarit `profiles.html` en rendant le sous-titre paramétrable.
🦺 Ne pas afficher les emails des `forum_profile`
> [FORUM PROFILE] afficher les contributeurs authentifiés les plus actifs sur les 30 derniers jours

- lacommunaute/surveys/tests/test_views.py
- lacommunaute/surveys/views.py
- lacommunaute/templates/partials/header_nav_secondary_items.html
- lacommunaute/templates/surveys/dsp_form.html
🎸 Donner du contexte aux utilisateurs non authentifiés qui tenteraient d'accèder au DSP : 
* suppression du `LoginRequired`
* ajout de contenus explicatifs
* accès direct au Tally pour les utilisateurs non authentifiés
🎨 UI
Utilisateur authentifié sans droit d'accès
Utilisateur non authentifié
Utilisateur avec droits d'accès
> [DSP] Améliorer l'onboarding

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/notification/tests/tests_utils.py
- lacommunaute/notification/utils.py
- lacommunaute/templates/partials/banners/call_for_contributers.html
- lacommunaute/templates/partials/banners/emplois_helpdesk.html
- lacommunaute/templates/partials/header_nav_secondary_items.html
🎸 `test_update_by_anonymous_user` casse lorsqu'un mot FR avec accent apparait => utiliser une suite de caractères minuscules à la place
🎸 `test_add_user_to_list_when_register` casse aléatoire à cause d'un ordre variable de la liste des `User` : ajout d'un tri dans `collect_new_users_for_onboarding`
🎸 les couleurs des bannières et badges ne sont plus conformes => mise à jour
🎨 UI
🚧 technique
Liens en Entete
Banniere documentation
Banniere nouveau sujet
> Corrections mineures : design et test fragile

- lacommunaute/forum_conversation/forms.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/forum_conversation/views_htmx.py
- lacommunaute/forum_moderation/utils.py
- lacommunaute/templates/forum_conversation/partials/post_feed_form_collapsable.html
- lacommunaute/templates/forum_conversation/partials/post_feed_form_errors.html
🎸 Empecher l'enregistrement des messages non conformes au lieu de les désapprouver puis de les reprendre manuellement.
🚧 technique
🦺 La vue htmx de création de `post` dans le fil des messages gère désormais l'affichage des erreurs dans le formulaire au lieu de générer une erreur 500.
🦺 Le contrôle du contenu des messages est centralisé dans `CreateUpdatePostMixin`
🦺 Le `rendering` du champ `content` du modèle `Post` n'est pas encore executé lors de l'execution de la méthode `clean` du formulaire. L'extraction du contenu en markdown est ajouté en début de méthode `check_post_approbation`
Affichage d'une erreur dans les formulaires classic django : `CreateView` et `UpdateView`
Affichage d'une erreur dans le …
> [MODERATION] bloquer les messages de spams

- lacommunaute/pages/tests/test_homepage.py
- lacommunaute/pages/views.py
- lacommunaute/templates/event/event_detail.html
- lacommunaute/templates/event/partials/event_date.html
- lacommunaute/templates/pages/home.html
🎸 Ajouter un quatrième cadre avec les 4 prochains évènements, leur date et un lien vers la page de l'évènement
🎸 Ajouter un lien vers la page des évènements du mois en cours
> [HOMEPAGE] afficher les évènements à venir

- lacommunaute/forum_member/tests/tests_view.py
- lacommunaute/forum_member/views.py
- lacommunaute/templates/partials/footer.html
suite de la PR #567 
🎸 ajout d'un lien dans le footer
🎸 tri des `forum_profile` par date de mise à jour decroissante
🎨 UI
🚧 technique
> [PROFILE] experimentation mon stage CIP - complements

- lacommunaute/forum_member/forms.py
- lacommunaute/forum_member/tests/tests_view.py
- lacommunaute/forum_member/urls.py
- lacommunaute/forum_member/views.py
- lacommunaute/templates/forum_member/moderator_profiles.html
- locale/fr/LC_MESSAGES/django.po
🎸 Les forums privés sont dépréciés. Le mécanisme d'invitation n'est plus maintenu.
🚧 technique
🦺 retrait de code mort pour alléger la dette technique
> [FORUM] suppression des liens d'invitations dans des forums privés

- config/settings/base.py
🎸 Machina s'appuie sur la librairie `markdown2` pour le rendu des contenus des messages (`post.content`)
🎸 L'avantage principal est de nettoyer le texte en remplaçant le code html saisi par l'utilisateur, par `[HTML_REMOVED`]
🎸 Cette substitution est utiliser dans la protection contre les spams.
🦺 Cependant, `markdown2` converti les `_` en balise markdown (`<em>`), ayant pour effet de casser le traitement de l'urlizer sur une url contenant des underscore.
🦺 L'ajout du package `code-friendly` dans la configuration de `markdown2` résout ce problème.
🚧 technique
* Le setup par défaut des settings de `machina` pour `MACHINA_MARKUP_LANGUAGE`
est `('machina.core.markdown.markdown', {'safe_mode': True, 'extras': …
> [POST] proteger les underscores dans les urls

- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum/forum_list.html
🎸 Corriger l'affichage du bouton "ajouter une fiche pratique" quand la catégorie n'en contient pas encore
Catégorie sans fiche pratique
Catégorie avec fiches pratiques existantes
> [DOCUMENTATION] création de la premiere fiche de la catégorie (fix)

- lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/templates/forum_conversation/partials/poster.html
- lacommunaute/templates/forum_conversation/topic_list.html
🎸 Afficher le forum de publication de message, à la suite des infos du poster
🦺 Passage du parametre `forum` à l'include `poster`
Avec mention du forum
Sans mention du forum
> feat(poster): désambiguer la mention du forum, de celle des tags

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/views.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/templates/forum_conversation/partials/topic_tags.html
🎸 Permettre d'activer le filtre des `Topic` en cliquant sur le `Tag` dans la liste
🎸 Ajouter le filtre sur `Tag` dans la vue `ForumView` pour éviter les inconsistences UI, bien que cette page sera revue avec #612 et #619
> feat(tags): rendre les tags clickables

- lacommunaute/templates/partials/header_nav_secondary_items.html
🎸 suppression du lien "mon stage CIP". le lien reste accessible dans le footer.
🎸 suppression de la mise en valeur du lien 'diag parcours IAE'
🎸 fix de la classe sur le lien documentation
🎨 UI
🚧 technique
> feat: Mise à jour de l'entête

- lacommunaute/forum/forms.py
- lacommunaute/forum/tests/test_forum_updateview.py
- lacommunaute/forum/tests/tests_forms.py
- lacommunaute/templates/forum/partials/forum_form.html
🎸 Permettre la mise à jour de la bannière d'un forum depuis le formulaire de creation et de mise à jour
🦺 Les fichiers générés par les tests ne sont pas supprimés du bucket minio
> feat: mise à jour de la bannière d'un forum

- .github/workflows/release-please.yml
🎸 Mise à jour de l'action `release-please`
🚧 technique
🦺 google-github-actions/release-please-action is deprecated, please use googleapis/release-please-action instead
> fix: Mise à jour de l'action `release-please`

- lacommunaute/surveys/tests/__snapshots__/test_views.ambr
- lacommunaute/templates/surveys/dsp_detail.html
- lacommunaute/templates/surveys/dsp_form.html
🎸 masquer la carte des fiches pratiques liées lorsqu'elle est vide
> fix: Diag parcours IAE - masquer la carte des fiches pratiques liées lorsqu'elle est vide

- lacommunaute/templates/forum_conversation/partials/post_feed.html
- lacommunaute/templates/layouts/base.html
- pyproject.toml
🎸 correction du formatage des balises scripts dans le gabarit `base.html`, en lien avec [l'issue 824 djlint](https://github.com/djlint/djLint/issues/824) : set `tool.djlint.format_js` à `false
🎸 mise à jour des paramètres des linters dans `pyproject.toml` pour résoudre les warning de l'issue #648 
🚧 technique
> fix(quality): formatage des balises `script` dans le gabarit `base.html`

- lacommunaute/static/stylesheets/itou_communaute.scss
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum/forum_list.html
- lacommunaute/templates/forum/partials/forum_banner.html
🎸 Améliorer l'affichage des bannières des fiches pratiques
🦺 suppression du gabarit mutualisé `forum_banner.html`
> fix(documentation): améliorer l'affichage des bannières des fiches pratiques

- lacommunaute/forum_stats/tests/tests_views.py
- lacommunaute/forum_stats/urls.py
- lacommunaute/forum_stats/views.py
- lacommunaute/templates/forum_stats/monthly_visitors.html
- lacommunaute/templates/forum_stats/statistiques.html
🎸 Ajout de la vue historique des visiteurs mensuels, en complément du funnel de la vue `statistiques`
🎸 Ajout des liens de navigation entre la vue `monthly_visitors` et la vue `statistiques`
lien cliquable sur la page statistiques principale
> feat(stats): ajout de la vue historique des visiteurs mensuels

- lacommunaute/forum_stats/tests/tests_views.py
- lacommunaute/forum_stats/urls.py
- lacommunaute/forum_stats/views.py
🎸 renommage de la vue `MonthlyVisitorsView`
🎸 utilisation de `reverse` dans les tests pour générer les url dynamiquement 🙄 
🚧 technique
> fix(stats): corrections mineures

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/views.py
- lacommunaute/forum_conversation/admin.py
- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_models.py
- lacommunaute/templates/forum/forum_detail.html
🎸 Afficher les annonces dans le fil des messages
🎸 Supprimer l'onglet annonce dans la vue d'un `Forum`
> feat(forum_conversation): remettre les annonces dans la liste des messages par défaut

- lacommunaute/forum_stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_stats/tests/tests_views.py
- lacommunaute/forum_stats/urls.py
- lacommunaute/forum_stats/views.py
- lacommunaute/templates/forum_stats/base_detail_stats.html
- lacommunaute/templates/forum_stats/daily_dsp.html
- lacommunaute/templates/forum_stats/monthly_visitors.html
- lacommunaute/templates/forum_stats/statistiques.html
🎸 Afficher dans la page `statistiques`, le nombre de `dsp` généré depuis le lancement de l'expé
🎸 Afficher à partir de la page `statistiques`, le graphe de nombre de `dsp` quotidiens sur les 3 derniers mois
🦺 mutualisation de la génération des vues de détails et de leur templates avec `MonthlyVisitorsView`
vue de la page `statistique`
vue de la page de détail
> feat(stats): afficher les stats quotidiennes des Diagnostics Parcours IAE

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/templates/forum_conversation/partials/topic_tags.html
🎸 forcer le paramètre page=1 sur les liens de filtrage sur tag dans la liste des topics, en utilisant url_add_query [templatetag](https://github.com/gip-inclusion/itou-communaute-django/blob/5c74c5601c134f0f8adaa07c1f758dde3fa1b887/lacommunaute/utils/templatetags/url_add_query.py#L11) dans topic_tags.html [ref](https://github.com/gip-inclusion/itou-communaute-django/blob/5c74c5601c134f0f8adaa07c1f758dde3fa1b887/lacommunaute/templates/forum_conversation/partials/topic_tags.html#L3)
Réplication du problème :
Avec le fix :
> fix(forum_conversation): page 1 forcée dans les liens tags

- lacommunaute/forum_conversation/tests/tests_views.py
> feat(forum_conversation/tests.py): test explicite pour la seconde page

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/views.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_conversation/urls.py
- lacommunaute/forum_conversation/view_mixins.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/forum_conversation/views_htmx.py
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum_conversation/partials/topic_filter.html
🎸 soutenir filtration sur `ForumView`
🎸 supprimer `ForumTopicListView`, l'accès pour HTMX fournis par `ForumView`
🎸 `FilteredTopicsListViewMixin` pour éviter la répétition de logique entre les views du Forum et l'espace d'échanges
🥁 Changement de rupture (modification ou caractéristique qui empêcherait une fonctionnalité existante de fonctionner comme prévu) nécéssitant une mise à jour de la documentation
> feat(forum): harmoniser la liste des topics

- scripts/import-latest-db-backup.sh
🎸 L'ajout de `minio` dans la stack `docker` a fait apparaitre un effet indesirable lors de l'import de db.
1. en fin d'import, tous les conteneurs étaient éteints
2. puis seul le conteneur `postgres` était relancés
La modification consiste à n'eteindre que le conteneur `postgres` pour le relancer ensuite, et laisser en fonctionnement `minio` et éventuellement `django`
🚧 technique
> chore(docker): Meilleur redemarrage des conteneurs docker en fin d'import de base de données

- lacommunaute/forum_stats/management/commands/collect_matomo_stats.py
- lacommunaute/forum_stats/tests/tests_management_commands.py
🎸 Rechercher la derniere date uniquement sur les stats matomo
🚧 technique
🦺 stats matomo : `["nb_uniq_visitors", "nb_uniq_visitors_returning", "nb_uniq_active_visitors", "nb_uniq_engaged_visitors"]`
> fix(stats): derniere date collectée des stats matomo

- lacommunaute/templates/layouts/base.html
🎸 suppression du tag manager matomo non exploité dans l'extraction des statistiques
🚧 technique
> chore: suppression du tag manager matomo

- lacommunaute/stats/admin.py
🎸 rendre la période de la statistiques plus explicite
🎸 filtrer uniquement sur les forums ayant des stats (actuellement les forums de documentation)
🎨 changement d'UI / ADMIN
🚧 technique
Admin Stat
Admin ForumStat
> feat(admin): améliorer le filtrage des stats de forum

- lacommunaute/forum/factories.py
- lacommunaute/forum/models.py
- lacommunaute/forum/tests/tests_model.py
- lacommunaute/stats/factories.py
- lacommunaute/stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/stats/tests/tests_views.py
- lacommunaute/stats/urls.py
- lacommunaute/stats/views.py
- lacommunaute/templates/stats/forum_stat_week_archive.html
🎸 Ajout d'une `WeekArchiveView` basée sur le modèle `ForumStat`
🎸 Ajout en contexte des stats de visiteurs à la période consultée
🎸 Ajout de la liste des `Forum` les plus notés (au moins 2 notes) sur la période consultée
🦺 factorisation de la génération des stats des visiteurs : utilisés dans 2 vues
🦺 pagination vers les semaines existantes, pas d'accès aux semaines futures
🦺 affichage des forums les plus vus, limités à 15
> feat(stats): page hebdo partenaires fiches pratiques

- lacommunaute/templates/pages/home.html
🎸 Tester la mise en avant d'une zone éditoriale sur la page d'accueil et suivre le traffic via matomo
🦺 code static, projet d'xp avec wagtail si test concluant
> feat(home): MVP zone editoriale sur la page d'accueil

- poetry.lock
- requirements/base.txt
- requirements/dev.txt
🛸 mise à jour dépendances
🚧 technique
- Updating sqlparse (0.5.0 -> 0.5.1)
- Updating botocore (1.34.137 -> 1.34.150)
- Updating certifi (2024.6.2 -> 2024.7.4)
- Updating django (5.0.6 -> 5.0.7)
- Updating tomlkit (0.12.5 -> 0.13.0)
- Updating cryptography (42.0.8 -> 43.0.0)
- Updating boto3 (1.34.137 -> 1.34.150)
- Updating django-compressor (4.5 -> 4.5.1)
- Updating identify (2.5.36 -> 2.6.0)
- Updating markdown2 (2.4.13 -> 2.5.0)
- Updating pytest (8.2.2 -> 8.3.2)
- Updating django-storages (1.14.3 -> 1.14.4)
- Updating sentry-sdk (1.45.0 -> 1.45.1)
> chore: update dependencies

- lacommunaute/forum/forms.py
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/views.py
- lacommunaute/templates/layouts/base.html
🎸 Lorsqu'une image est définie pour un `forum`, alimenter la vignette opengraph avec, au lieu de l'image par défaut
🦺  images privées stockées dans un bucket
Vue des `forum` d'une catégorie
Vue d'un `forum`
vignette du `forum` lors du partage
> feat(forum): utiliser l'image du forum dans la vignette opengraph

- lacommunaute/templates/layouts/base.html
🎸 rollback #723 
🚧 technique
🦺 la clé publique du projet de la communauté dans sentry est `315…8f2`
> fix: mise à jour de la public key sentry pour l'envoi des logs

- config/settings/base.py
- lacommunaute/forum/forms.py
- lacommunaute/forum/tests/test_forum_updateview.py
Quelque chose que je viens d'implementer sur les-emplois, j'ai vu l'occasion de repliquer le travail sur la communauté :)
🎸 Ajouté une définition des formats d'image acceptés (encouragés) sur les thématiques
🎸 Ajouté un champ dans le settings du projet pour clarifier les formats d'image soutenu. J'ai choisis les formats d'image qui sont [soutenu par le plupart des navigateurs mondiales](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support)
🦺 J'ai inclus GIF 😁
> feat(forum): attr accept définit sur forms.ImageField

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum/forum_documentation.html
🎸 utiliser la balise `article` au lieu de la balise `div` pour la description des `forum`
🎸 appliquer la classe `img-fluid` sur le rendu des images dans la description des `forum`
> fix(forum): balise `article` et dimension des images

- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/forum_conversation/views_htmx.py
- lacommunaute/notification/admin.py
- lacommunaute/notification/factories.py
- lacommunaute/notification/models.py
- lacommunaute/notification/tests/tests_models.py
🎸 Quand un utilisateur voit un sujet, les notifications liés sont marqués lues
🎸 Adjustment des champs inclus dans la classe `NotificationAdmin`
🚧 technique
> feat(notification): passage des notifications en lues

- lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/templates/forum_conversation/topic_create_check.html
🎸 suite #681
🎸 le parametre `?checked=1` génère du bruit dans la suite de test. simplification en `?checked`
🚧 technique
> fix(upvote): supprimer un parametrage ambigue

- lacommunaute/forum/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/templates/partials/upvotes.html
🎸 fix ui
🚧 technique
🦺 refactor des tests
> fix(upvotes): largeur du bouton s'abonner dynamique

- lacommunaute/forum_conversation/forms.py
- lacommunaute/forum_conversation/tests/tests_forms.py
🎸 Les `Post` de réponse d'un `Topic` (à partir du 2e, jusqu'au dernier), conservent le même sujet que le `Topic`. Le `TOPIC_ANSWER_SUBJECT_PREFIX` est supprimé pour améliorer la qualité des emails de notification.
🎸 Optimisation & simplification de `TopicForm` et `PostForm`
🚧 technique
🦺 Suppression du code dupliqué dans `PostForm` et dans `TopicForm` avec le code de `django-machina`, et ajout des tests correspondants
🦺 Simplification de la méthode `init` de `TopicForm`, et ajout des tests correspondants
> fix(post): simplification du sujet des `Post`

- lacommunaute/forum_conversation/tests/tests_forms.py
🎸 `faker.sentences(2)` produit des contenus considérés comme -Non-FR- par la lib `langdetect` malgré le paramétrage `Faker(settings.LANGUAGE_CODE)`.
🎸 Remplacement de la génération de 2 phrases, par un paragraphe de 5 phrases : `faker.paragraph(nb_sentences=5)` dans les tests des formulaires de l'app `forum_conversation`
🚧 technique
> fix(forum_conversation): Résolution des erreurs de tests sur les contenus des messages

- lacommunaute/forum_conversation/forms.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/templates/forum_conversation/partials/post_form.html
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- lacommunaute/templates/forum_conversation/partials/topic_tags.html
- lacommunaute/templates/partials/form_field.html
🎸 Les formulaires de création et mise à jour de `Topic` doit permettre d'ajouter un `tag` qui n'existe pas encore
ISSUE #726 partie 1
🦺 PR préparatoire à l'ajout de `tag` sur les `Forum`
🦺 UI fix : déplacer la case `verrouiller le sujet` en dehors du panneau "Etiquette"
🦺 UI fix : mise à jour du format de la case à cocher `checkboxinput` dans le template `partials/form_field`
🎨 mise à jour class `tag` sur les tags en remplacement des badges
Nouveau sujet
Mise à jour d'un sujet existant (case "Verrouiller le sujet")
Vue d'un tag sur un message au format `tag`
> feat(tags): ajouter une étiquette inexistante à un sujet

- lacommunaute/forum/tests/__snapshots__/test_forum_updateview.ambr
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/views.py
🎸 Réduire la liste des `Forum` enfants affichés en filtrant sur leurs tags
suite #746 
🦺 Affichage des enfants, les petits-enfants ne sont pas considérés, qu'il possède le tag ou non
> feat(tags): filtrer les `forum` enfants à partir des tags

- lacommunaute/pages/sitemaps.py
- lacommunaute/pages/tests/test_sitemap.py
- lacommunaute/pages/urls.py
🎸 Referencer les fiches partenaires dans sitemap.xml
🚧 technique
🦺 Parametrisation des tests de `Topic`, `Forum` et `Partner`
🦺 suite de #757
> feat(partner): referencer les fiches partenaires dans sitemap.xml

- lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
- lacommunaute/stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/stats/urls.py
- lacommunaute/templates/partials/footer.html
- lacommunaute/templates/stats/forum_stat_week_archive.html
🎸 pour plus de consistence
🚧 technique
🦺 nouvelle route pour les stats hebdo : `/statistiques/weekly/YYYY/WW/`
> fix: mise à jour des urls de statistiques

- lacommunaute/stats/factories.py
- lacommunaute/stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/stats/tests/tests_views.py
- lacommunaute/stats/urls.py
- lacommunaute/stats/views.py
- lacommunaute/templates/stats/forum_stat_week_archive.html
- lacommunaute/templates/stats/statistiques.html
🎸 Vue de redirection vers la plus récente `ForumStatWeekArchiveView` possible, sinon `404`
vue de la page stats avec le nouveau lien sous forme de bouton
vue des nouveaux titres de section de la page hebdo
> feat(stats): ajout d'un lien vers la page de stats hebdos

- Makefile
- README.md
- scripts/import-latest-db-backup.sh
🎸 Ajout de la commande `resetdb` dans le fichier `Makefile` pour automatiser l'hydratation d'une DB de dev
🎸 Amélioration du script de restauration des dump de DB : suppression surcouche `docker`, ajout des migrations
🚧 technique
> chore(db): Améliorer l'hydratation de la base de données en developpement

- poetry.lock
- requirements/base.txt
- requirements/dev.txt
🛸 mise à jour des dépendances
- Updating idna (3.8 -> 3.10)
- Updating urllib3 (2.2.2 -> 2.2.3)
- Updating anyio (4.4.0 -> 4.6.0)
- Updating botocore (1.35.14 -> 1.35.24)
- Updating platformdirs (4.3.2 -> 4.3.6)
- Updating filelock (3.16.0 -> 3.16.1)
- Updating boto3 (1.35.14 -> 1.35.24)
- Updating faker (28.4.1 -> 29.0.0)
- Updating identify (2.6.0 -> 2.6.1)
- Updating pytest (8.3.2 -> 8.3.3)
- Updating regex (2024.7.24 -> 2024.9.11)
- Updating virtualenv (20.26.4 -> 20.26.5)
- Updating sentry-sdk (2.13.0 -> 2.14.0)
🚧 technique
> chore: mise à jour des dépendances

- .env.template
- Makefile
- config/settings/base.py
- lacommunaute/templates/middleware/parking.html
- lacommunaute/utils/middleware.py
- lacommunaute/utils/tests/tests_middleware.py
🎸 Ajout d'un `middleware` pour activer une page parking lors des maintenances techniques à venir : migration IC #731 , et migration de la documentation #765
🚧 technique
🦺 Ajout de la variable d'environnement `PARKING_PAGE`
🦺 `ParkingPageMiddleware` attrape toutes les requêtes sauf celles vers l'admin lorsqu'il est actif.
🦺 exclure le template `parking.html` du contrôle de `djlint` dans la CI (`make quality`)
page parking
> feat: page parking

- lacommunaute/forum/forms.py
- lacommunaute/forum/tests/tests_forms.py
- lacommunaute/partner/forms.py
- lacommunaute/partner/tests/__snapshots__/tests_partner_detailview.ambr
- lacommunaute/partner/tests/tests_forms.py
- lacommunaute/partner/tests/tests_partner_createview.py
- lacommunaute/partner/tests/tests_partner_listview.py
- lacommunaute/partner/tests/tests_partner_updateview.py
- lacommunaute/partner/urls.py
- lacommunaute/partner/views.py
- lacommunaute/templates/partner/create_or_update.html
- lacommunaute/templates/partner/detail.html
- lacommunaute/templates/partner/list.html
- lacommunaute/templates/partner/partials/partner_form.html
- lacommunaute/utils/html.py
- lacommunaute/utils/tests/tests_utils.py
🎸 Permettre l'ajout et la mise à jour des `Partner` depuis la page `partner:list`
🎸 Accès limité aux super-utilisateurs
🦺 factorisation de la méthode `wrap_iframe_in_div_tag`
🦺 mixin et template communs pour `PartnerCreateView` et `PartnerUpdateView`
> feat(partner): ajout des pages de creation / mise à jour depuis la page "nos partenaires"

- lacommunaute/static/stylesheets/itou_communaute.scss
- lacommunaute/stats/factories.py
- lacommunaute/stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/stats/tests/tests_views.py
- lacommunaute/stats/urls.py
- lacommunaute/stats/views.py
- lacommunaute/templates/stats/documents.html
- lacommunaute/templates/stats/statistiques.html
- lacommunaute/utils/templatetags/date_filters.py
- lacommunaute/utils/tests/tests_utils.py
🎸 Vue `DocumentStats` pour afficher le temps de lecture cumulé, le nombre de visites, le nombre de notation et la moyenne de notations, de toutes les fiches pratiques.
🦺 les annotations de `ForumStats` et `ForumRating` sont associées via une `SubQuery`
🦺 ajout du templatetag `convert_seconds_into_hours`
🦺 mise à jour de la factory `ForumStatFactory` pour déterminer les valeurs de `visits`, `entry_visits` et `time_spent`
🦺 tri des items par le passage d'un param `sort` dans l'url
page avec tri par défaut
page avec tri sur le nombre de visites
bas de la page statistiques avec le lien vers la nouvelle vue
> feat(stats): page de statistique des fiches pratiques

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum_conversation/enums.py
- lacommunaute/forum_conversation/factories.py
- lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/view_mixins.py
- lacommunaute/templates/forum_conversation/partials/topic_filter.html
- lacommunaute/templates/forum_conversation/partials/topic_tags.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/forum_conversation/topics_public.html
🎸 **suppression du paramètre `page=1` qui forçait le masquage de la zone de filtre**
🎸 **appel `htmx` de `TopicListView` lors du clic sur les tags, pour éviter tous les inconvénients d'un rechargement de page complet**
🎸 fiabilisation des tests sur les filtres x les étiquettes
🎸 desambiguation des paramètres dans le contexte de la vue `TopicListView`
🎸 suppression de la gestion d'une liste de `Tag` dans les url (non terminé), pour n'en gérer plus qu'un seul
🚧 technique
🦺 réécriture des tests concernés dans les commits pour améliorer la lisibilité (voir les passer en style `pytest`)
🦺 renommage des énums pour une meilleure présentation utilisateur
🦺 réécriture des tests de `ForumView` à voir …
> fix: filtrage des questions en utilisant les étiquettes

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum_conversation/enums.py
- lacommunaute/forum_conversation/factories.py
- lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/view_mixins.py
- lacommunaute/templates/forum_conversation/partials/topic_filter.html
- lacommunaute/templates/forum_conversation/partials/topic_tags.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/forum_conversation/topics_public.html
🦺 suite #794. fusion avant d'avoir poussé le rebasage
> fix: filtrage des questions en utilisant les étiquettes (part 2)

- lacommunaute/stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/stats/tests/tests_views.py
- lacommunaute/stats/views.py
- lacommunaute/templates/stats/documents.html
🎸 La catégorie est le `Forum` parent. Ajout en colonne + tri dessus
non trié
trié
> feat(stats): ajout de la colonne categorie dans les stats des fiches pratiques

- lacommunaute/utils/templatetags/attachments_tags.py
- lacommunaute/utils/tests/tests_utils.py
🎸 Le templatetag `is_available` retourne à tord que le fichier n'est pas disponible.
🎸 Remplacer le test par la recherche de la taille du fichier, assorti  d'un `try/except` si le fichier n'est pas trouvé
🚧 technique
🦺 pourquoi  `object.file.field.storage.exists(object.file.name)` ne fonctionne pas ou plus ???
état actuel non désiré (https://communaute.inclusion.beta.gouv.fr/forum/espace-d%C3%A9changes-113/topic/passage-de-titre-cip-2168/)
état desiré
> fix(attachment): affichage des liens vers les fichiers des messages

- config/settings/dev.py
- docker-compose.yml
🎸 mailhog devient inutile en env de dev avec le deploiement de la #731 
🚧 technique
> chore: suppression de mailhog (dev)

- .gitignore
- clevercloud/cron.json
🦺 le calcul des rapports matomo prend plus de temps qu'avant octobre 2024
🚧 technique
> fix: retarder la collecte des statistiques matomo

- lacommunaute/stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/templates/stats/documents.html
🎸 lien cassé vers les forums, colonne "fiche pratique"
🦺 forum.get_absolute_url
> fix(stats): ajout des liens vers les forums dans la page de statistique des fiches pratiques

- config/settings/base.py
- config/settings/dev.py
- config/urls.py
- lacommunaute/templates/layouts/base.html
- lacommunaute/users/tests/__snapshots__/tests_views.ambr
- lacommunaute/users/tests/tests_views.py
- lacommunaute/users/views.py
- lacommunaute/utils/enums.py
- lacommunaute/utils/settings_context_processors.py
- lacommunaute/utils/tests/tests_middleware.py
- lacommunaute/utils/tests/tests_urls.py
🎸 lorsque le mode DEBUG est actif:
* afficher le lien magique de connexion au lieu d'utiliser les routes `django.contrib.auth.urls`
* afficher une bannière rouge
🚧 technique
🦺 passage de la valeur de la variable `DEBUG` dans le `context_processor`
Banniere Debug Mode
Lien cliquable d'authentification en mode debug
> chore: login in debug/dev mode

- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_models.py
- lacommunaute/pages/tests/test_homepage.py
- lacommunaute/pages/views.py
- lacommunaute/partner/tests/tests_partner_listview.py
- lacommunaute/templates/forum_conversation/topic_simple_list.html
- lacommunaute/templates/pages/home.html
🎸 Valoriser les questions en attente de réponse dès la page d'acceuil, et permettre d'y répondre directement
🎸 Allègement de l'affichage, les questions en attente ne peuvent pas avoir de réponse certifiée. Les `attachments` et les sondages sont volontairement non affichés.
🦺 ajout de la méthode `unanswered` dans `TopicQueryset`
🦺 duplication et simplification du  gabarit `topic_list` en `topic_simple_list`
🦺 enrichissement du contexte de `HomeView`
🦺 pas de pagination, seules les 4 plus récentes questions sont affichées. La section est cachée si aucune question n'est en attente
page d'accueil avec questions en attente
page d'accueil sans question en attente
> feat(home): afficher les questions en attente de réponse sur la page d'accueil

- config/settings/base.py
- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_tasks.py
- lacommunaute/users/tests/__snapshots__/tests_views.ambr
🎸 mise à jour de `DEFAULT_FROM_EMAIL` en `noreply@inclusion.gouv.fr`
🎸 suppression d'un param statique dans l'appel au gabarit `SIB_NEW_MESSAGE_TEMPLATE`
🚧 technique
> refactor: améliorations mineures appel à l'API Brevo

- lacommunaute/forum/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_upvote/tests/test_forumupvoteview.py
- lacommunaute/forum_upvote/tests/test_postupvoteview.py
- lacommunaute/templates/partials/header.html
- lacommunaute/templates/partials/upvotes.html
- locale/fr/LC_MESSAGES/django.po
🎸 Renommer les `UpVotes`, de `sauvegardes` en `abonnements`. 
`/upvotes/`
`Forum`
`Post`
`user menu`
> feat: renommage des upvotes

- lacommunaute/templates/registration/login_with_magic_link.html
- lacommunaute/users/tests/__snapshots__/tests_views.ambr
- lacommunaute/users/tests/tests_views.py
🎸 param non valorizé à tort
🦺 extension des tests
> fix: hydratation du parametre `next` dans l'url proconnect:authorize

- config/settings/base.py
- lacommunaute/openid_connect/middleware.py
- lacommunaute/openid_connect/tests/test_middleware.py
Partie 1 : les emplois > la commu
Scope : Orienteurs et SIAE
🎸 Permettre à un utilisateur authentifié dans le site des emplois via ProConnect, d'être automatiquement connecté via ProConnect dans la communauté
🦺 capture du paramètre `proconnect_login` dans l'url par un `middleware` dédié
🦺 retraitement de l'url pour supprimer le paramètre `proconnect_login` dans tous les cas
> feat: POC, autoconnection les emplois vers la commu via Pro Connect

- .github/workflows/ci.yml
- README.md
- clevercloud/python.json
- config/settings/base.py
🎸 Utilisation du backend `django.core.cache.backends.db.DatabaseCache`
🚧 technique
🦺 enjeux : 2 enregistrements uniquement
> chore: modification de la stratégie de mise en cache

- clevercloud/cron.json
- lacommunaute/stats/tests/__snapshots__/tests_views.ambr
- lacommunaute/stats/views.py
🐛 Le calcul des rapports de données matomo bagotte. Les données obtenues sont erronées et nécessitent une reprise manuelle au moins 2 fois/semaine.
⚠️ la collecte automatique est desactivée.
🪲 Bug externe
🚧 technique
> fix(stats): desactivation de la collecte des stats automatique

- lacommunaute/conftest.py
- pytest.ini
🦺  `DatabaseCache` => tests ok
🦺 `DatabaseCache` => tests KO 🧧 
```
FAILED lacommunaute/forum/tests/tests_views.py::ForumViewTest::test_filtered_queryset_on_tag - AssertionError: 32 != 20 : 32 queries executed, 20 expected
FAILED lacommunaute/forum/tests/tests_views.py::TestDocumentationCategoryForumContent::test_numqueries_on_tags - Failed: Expected to perform 19 queries but 31 were done (add -v option to show queries)
FAILED lacommunaute/forum_conversation/tests/tests_views.py::TopicViewTest::test_numqueries - AssertionError: 51 != 39 : 51 queries executed, 39 expected
FAILED lacommunaute/stats/tests/tests_views.py::TestForumStatView::test_num_queries - Failed: Expected to perform 7 queries but 19 were done (add -v option to show queries)
FAILED …
```
> chore: mise en cache en environnement de developpement

- lacommunaute/forum/tests/tests_model.py
- lacommunaute/forum_conversation/admin.py
- lacommunaute/forum_conversation/factories.py
- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_models.py
🎸 Il est apparu un cas de `Topic` où `posts_count` était supérieur à zéro après la suppression du `Post` associé via l'admin.
🎸 Ce `Topic` a fait échouer en erreur 500, l'affichage des listes de `Topic`, lors de la tentative d'affichage des données de détail du `first_post`
🪭 Issue #860, https://inclusion.sentry.io/issues/14670791/?project=4508410606452816
🪭 Cas reproduit en supprimant des `Post` depuis la liste dans l'admin
🪭 Cause identifiée : la méthode `delete_selected` n'appelle pas la méthode `delete` de `machina` sur ces objets. Les données dénormalisées des `Topic` associés ne sont pas mises à jour.
🧦 Patch : desactivation de la méthode `delete_selected` dans l'admin
🚧 technique
🦺 factorisation des paramètres …
> fix: 🦇 désactiver la suppression en masse des `Post` depuis l'admin django

- .env.template
- .github/workflows/ci.yml
- .github/workflows/review-app-creation.yml
- config/settings/base.py
- config/settings/dev.py
- config/settings/test.py
- docker/django/entrypoint.sh
- lacommunaute/notification/emails.py
- lacommunaute/notification/tasks.py
- lacommunaute/notification/tests/tests_emails.py
- lacommunaute/notification/tests/tests_tasks.py
- lacommunaute/partner/migrations/0001_initial.py
- lacommunaute/users/tests/__snapshots__/tests_views.ambr
- lacommunaute/users/tests/tests_views.py
- lacommunaute/users/views.py
- lacommunaute/utils/enums.py
- pyproject.toml
- pytest.ini
- scripts/import-latest-db-backup.sh
🎸 Isoler les `settings` de test, pour nettoyer les valeurs par défaut des `settings` de base et de dev.
🎸 Utiliser ces `settings` de test pour rendre les tests executables dès le tirage du dépôt.
🎸 Utiliser ces `settings` dans la `CI` pour harmoniser l'execution des tests en local et dans les actions  github
🚧 technique
🦺 refactor de l'appel aux settings liés aux envois de mails
🦺 simplification de la gestion des routes `brevo`
🦺 harmonisation des `settings` utilisés pour envoyer le lien magique par mail ou dans les `message` django
🦺 prise en compte des noms de bucket issus des `settings` dans les fichiers de migration
📦 prerequis à la PR #857
> refactor: isoler les settings de test

- config/settings/base.py
- config/settings/test.py
- lacommunaute/search/__snapshots__/tests.ambr
- lacommunaute/search/tests.py
- lacommunaute/templates/forum_conversation/partials/topic_tags.html
- lacommunaute/templates/forum_conversation/topic_list.html
- lacommunaute/templates/partials/header.html
- lacommunaute/templates/partials/pagination.html
- lacommunaute/templates/search/commonindex_list.html
- lacommunaute/utils/settings_context_processors.py
- lacommunaute/utils/templatetags/url_query_tags.py
- lacommunaute/utils/tests/tests_context_processor.py
- lacommunaute/utils/tests/tests_middleware.py
- lacommunaute/utils/tests/tests_utils.py
🎸 ajout de 2 liens vers les recherches du site des emplois :
- `/search/prescribers`
- `/search/employers`
🎸 si l'utilisateur est connecté, et son `identity_provider` est _proconnect_, ajout des `query_params` pour le réauthentifier automatiquement sur le site des emplois. 
🎸 positionnement des liens : 
- page de recherche
- menu déroulant des utilisateurs connectés
> feat(search): ajout de liens de recherche vers le site des emplois

- clevercloud/cron.json
- config/settings/base.py
- lacommunaute/notification/admin.py
- lacommunaute/notification/factories.py
- lacommunaute/notification/management/commands/delete_old_email_sent_tracks.py
- lacommunaute/notification/models.py
- lacommunaute/notification/tests/tests_management_commands.py
- lacommunaute/notification/tests/tests_models.py
- lacommunaute/utils/factory_boy.py
🎸 L'application trace dans `EmailSentTrack` les appels à `brevo` et le code retour de leur API. Ces objets contiennent des données visées par le champ de la RGPD. Leur seul objectif est de pouvoir identifier l'apparition d'un problème lors de l'appel à l'API. Elles ne sont pas utilisées par ailleurs. Supprimons les au bout de 90 jours.
🚧 technique
🦺 creation d'un nouveau logger. sera revu avec la mise en place de datadog (yc un json formatter)
🦺  ajout d'un filtre dans l'admin sur le `status_code` de l'api `brevo`
> feat: supprimer les traces d'envoi d'emails de plus de 90 jours

- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum_conversation/enums.py
- lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/view_mixins.py
🎸 La dernière réponse `certifiée` date de avril 2023. Masquons ce filtre avant de décider de supprimer intégralement cette fonctionnalité
> feat: masquer le filtre sur les reponses certifiees

- lacommunaute/forum/tests/test_categoryforum_createview.py
- lacommunaute/forum/tests/test_categoryforum_listview.py
- lacommunaute/forum/tests/test_forum_updateview.py
- lacommunaute/forum/tests/test_subcategoryforum_createview.py
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum/views.py
- lacommunaute/partner/tests/__snapshots__/tests_partner_detailview.ambr
- lacommunaute/partner/tests/tests_partner_createview.py
- lacommunaute/partner/tests/tests_partner_listview.py
- lacommunaute/partner/tests/tests_partner_updateview.py
- lacommunaute/partner/views.py
- lacommunaute/templates/forum/category_forum_list.html
- lacommunaute/templates/forum/forum_detail.html
- lacommunaute/templates/forum/forum_documentation_category.html
- lacommunaute/templates/partner/detail.html
- lacommunaute/templates/partner/list.html
🎸 permettre aux utilisateurs membre de l'équipe d'accèder aux vues de gestion des `Forum` et des `Partner`
🚧 technique
🦺 suite #913
> feat: extension des droits des utilisateurs de l'équipe - Documentation et Partenaires

- config/settings/base.py
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_models.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_upvote/tests/test_upvotelistview.py
- lacommunaute/notification/middleware.py
- lacommunaute/notification/tests/test_middleware.py
- lacommunaute/users/middleware.py
- lacommunaute/users/models.py
- lacommunaute/users/tests/tests_middleware.py
- lacommunaute/users/tests/tests_models.py
🎸 Creer ou mettre à jour `EmailLastSeen` lors des évènements suivants :
* navigation d'un utilisateur authentifié : dans un `middleware` dedié
* creation d'un `Post`/`Topic` : dans la méthode `save` du modèle `Post` 
* click sur une notification email : dans le middleware `NotificationMiddleware` de suivi des urls dans les mails de notification
🚧 technique
🦺 Les mises à jour de `Post` ne déclenche plus de mise à jour de `EmailLastSeen` pour éviter la détérioration de données en cas de `save` massif sur des instances existantes du modèle `Post`
🦺 Creation d'un `DSP`, d'un `UpVote` ou d'un `Event`, les vues sont en `LoginRequiredOnly`. L'enregistrement du passage de l'utilisateur est donc  déjà enregistré par …
> feat: enregistrer le dernier evenement connu pour une adresse mail

- config/settings/base.py
- lacommunaute/forum/tests/tests_views.py
- lacommunaute/forum_conversation/models.py
- lacommunaute/forum_conversation/tests/tests_models.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/tests/tests_views_htmx.py
- lacommunaute/forum_upvote/tests/test_upvotelistview.py
- lacommunaute/notification/middleware.py
- lacommunaute/notification/tests/test_middleware.py
- lacommunaute/users/management/commands/populate_emaillastseen.py
- lacommunaute/users/middleware.py
- lacommunaute/users/models.py
- lacommunaute/users/tests/tests_management_commands.py
- lacommunaute/users/tests/tests_middleware.py
- lacommunaute/users/tests/tests_models.py
🎸 Collecter les `User.last_login`, `Event`, `DSP`, `UpVote`, `ForumRating`, `Post` anonymes et authentifiés, `Notification` visitées (#891)
🎸 dédupliquer les emails en gardant l'evènement le plus récent
🎸 ignorer les emails déjà enregistrés dans `EmailLastSeen`, en considerant que l'enregistrement dans `EmailLastSeen` est le plus récent
🎸 Insérer l'ensemble dans `EmailLastSeen`
🚧 technique
🦺 `test_collect_clicked_notifs` casse par principe en attendant #891 
🦺 prérequis #892 & #894 
```
$ python manage.py populate_emaillastseen
INFO 2025-02-11 11:20:09,215 ./lacommunaute/users/management/commands/populate_emaillastseen.py : starting to populate EmailLastSeen table
INFO 2025-02-11 11:20:09,215 ./lacommunaute/users/management/commands/populate_emaillastseen.py : processing users
INFO …
```
> feat: hydrater la table du dernier évènement connu pour un email à partir des évènements passés

- config/settings/base.py
- lacommunaute/forum/tests/test_categoryforum_createview.py
- lacommunaute/forum/tests/test_subcategoryforum_createview.py
- lacommunaute/forum/views.py
- lacommunaute/utils/perms.py
- lacommunaute/utils/tests/tests_utils.py
🎸 cf titre
🚧 technique
🦺 les droits sont ajoutés à un groupe comprennant les utilisateurs `staff`.
🦺 le numéro du groupe est defini en dur dans les settings
> feat: extension des droits des utilisateurs de l'équipe - edition, deplacement et verrouillage des sujets

- clevercloud/cron.json
💥 instabilités quotidiennes matomo
🚧 technique
🦺 lignes retirées de la crontab
```
"0 6 * * * $ROOT/clevercloud/run_management_command.sh collect_matomo_stats",
"5 6 * * * $ROOT/clevercloud/run_management_command.sh collect_django_stats",
"10 6 1 * * $ROOT/clevercloud/run_management_command.sh collect_matomo_stats --period month",
"15 6 * * 1 $ROOT/clevercloud/run_management_command.sh collect_matomo_forum_stats",
```
> fix: desactivation de la collecte automatique des statistiques depuis matomo

- clevercloud/cron.json
🎸 La date `missyou_send_at` n'est pas mise à jour lors de l'envoi de la notification. 
⚠️ envoi en boucle toutes les heures aux 20 premiers destinataires
🚧 technique
> fix: mise en pause des notifications "vous nous manquez"

- lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
- lacommunaute/pages/tests/test_homepage.py
- lacommunaute/templates/pages/home.html
🎸 Marquer `safe` le champ `short_description` des `Forum` sur la page d'accueil
> fix: encodage de la description des fiches pratiques sur la homepage

- lacommunaute/forum/forms.py
- lacommunaute/forum/tests/test_categoryforum_createview.py
- lacommunaute/forum/tests/test_forum_updateview.py
- lacommunaute/forum/tests/test_subcategoryforum_createview.py
- lacommunaute/forum/tests/tests_forms.py
- lacommunaute/forum/views.py
- lacommunaute/templates/forum/partials/forum_form.html
🎸 La restriction de l'accès à l'admin `django` ne permet plus aux `staff` de déplacer une fiche pratique, d'une catégorie à une autre.
🎸 Autoriser la mise à jour du parent dans le formulaire de mise à jour d'une fiche pratique
🦺 Le parent est nécéssairement un `Forum` de type `FORUM_CAT` de niveau 0,
🦺 Le parent n'est pas accessible dans les formulaires de création, car il est déduit de la PK contenu dans la route à l'enregistrement,
🦺 Les `Forum` en dehors de l'espace documentaire ne sont pas concernés.
Mise à jour d'une fiche pratique : parent modifiable
Mise à jour d'une catégorie documentaire : parent non accessible
Création d'une nouvelle fiche pratique : parent non accessible
> feat: modifier la catégorie d'une fiche pratique par les utilisateurs `staff`

- lacommunaute/search/__snapshots__/tests.ambr
- lacommunaute/search/tests.py
- scripts/update_dependencies.sh
- uv.lock
🛸 Mise à jour des versions des dépendances
🚧 technique
🦺 correction d'un test devenu flakky
> chore: mise à jour des dependances

- clevercloud/cron.json
- lacommunaute/utils/tests/tests_consistency.py
- pyproject.toml
- uv.lock
🎸 ré-arrangement des tâches planifiées par fréquence > heure > minute
🧑‍🍳 la fréquence est le nombre d'executions attendues dans une année
🛸 ajout de la lib `python-crontab`
🚧 technique
🦺 ajout d'un test sur l'arrangement des tâches dans `cron.json` 
🦺 thks to @rsebille
> chore: rearrangement des tâches planifiées

- lacommunaute/forum_conversation/forms.py
- lacommunaute/forum_conversation/shortcuts.py
- lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_forms.py
- lacommunaute/forum_conversation/tests/tests_shortcuts.py
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_moderation/tests/test_moderation_queue_list.py
- lacommunaute/templates/forum_conversation/partials/post_form.html
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- lacommunaute/templates/forum_moderation/moderation_queue/list.html
🎸 Permettre aux utilisateurs `staff` de moderer un `Post` ou un `Topic` depuis le formulaire de mise à jour.
🎸 Le `Post` et/ou son `Topic` ne sont pas supprimés mais l'état `approved` est mis à `False`. Ils sont visibles dans la queue de moderation
🦺 Décision d'architecture
🦺 Lien avec d'autres PR
🦺 Code sensible
formulaire de mise à jour d'un `Topic` sans droit d'approbation (et mode anonyme)
formulaire de mise à jour d'un `Topic` avec droit d'approbation
formulaire de mise à jour d'un `Post` sans droit d'approbation (et mode anonyme)
formulaire de mise à jour d'un `Post` avec droit d'approbation
vue du formulaire de creation d'un `Topic` pour un `staff`
file d'attente de moderation
> feat: faciliter la moderation des `Post` pour les utilisateurs `staff`

- lacommunaute/forum_permission/migrations/0002_perms_update.py
🎸 fix #933 , ajout permission manquante `can_download_file`
> fix: ajout de l'autorisation `can_download_file`

- .github/workflows/ci.yml
- config/settings/base.py
- config/settings/test.py
- lacommunaute/utils/tests/tests_live_cellar.py
- pyproject.toml
- uv.lock
🔴  Tentative de mise à jour de `boto3` et `botocore` > 1.36
⚠️ L'implémentation S3 du PAAS CleverCloud ne supporte pas la nouvelle fonctionnalité de fonctions d'intégrité des données mise en place par AWS à partir de la 1.36 : [boto3 Issue 4392](https://github.com/boto/boto3/issues/4392), [boto3 Issue 4398](https://github.com/boto/boto3/issues/4398#issuecomment-2619946229)
⚠️ `minio` utilisé dans la `CI` et les tests en local supporte cette nouvelle fonctionnalité, et donc ne cassent pas.
🟢 desactivaition de la fonction d'intégrité des données
🟢 ajout d'un test activé par la `CI` uniquement pour contrôler la compatibilité entre l'app `django` et le `cellar` utilisé en production
🟢 ajout d'un test cassant tant que le `cellar` ne supporte pas le contrôle d'intégrité, en vue de le réactiver …
> chore: televersement des fichiers

- lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
- lacommunaute/forum_conversation/tests/tests_views.py
- lacommunaute/forum_conversation/views.py
- lacommunaute/templates/forum_conversation/partials/topic_form.html
- lacommunaute/templates/forum_conversation/post_update.html
🎸 Permettre aux utilisateurs `staff` de desapprouver des `Post` et des `Topic` enregistré par d'autres utilisateurs
reprise du sujet, suite à l'echec de la #928
🦺 utilisation d'une balise `name="unapprove"` dans le tag `<input type="submit"` pour distinguer la mise à jour de la désapprobation
🦺 les tentatives de desapprobation pour des utilisateurs non `staff` ne modifient pas la valeur de `approved`
silencieusement
> feat: desapprobation de contenus

- lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
- lacommunaute/templates/flatpages/default.html
- lacommunaute/templates/middleware/parking.html
- lacommunaute/templates/partials/header.html
Actuellement, le haut de page est géré dans l'admin de Django comme n'importe quel contenu modifiable.
Cela nous empêche de suivre les changements réalisés car le contenu n'est pas suivi par Git.
Le contenu étant dupliqué d'une page à l'autre, il est plus difficile à maintenir.
J'ai aussi corrigé une faute d'orthographe : République française (et non Rébublique).
Avant
Après
> Pages statiques : utilisation du haut de page par défaut

- lacommunaute/forum/migrations/0022_forum_forum_forum_tree_id_lft_idx.py
- lacommunaute/forum/models.py
L’index devrait être créé automatiquement par Django MPTT, mais il n’est pas créé pour Django 5.
https://github.com/django-mptt/django-mptt/commit/c169d90cf868ad5f0665d850706aaf5d3ef3923f
Le problème devrait être résolu avec https://github.com/django-mptt/django-mptt/pull/845.
🚧 technique (perfs, suite à l’incident clever cloud https://www.clevercloudstatus.com/incidents/1011)
> Ajouter un index sur les colonnes forum tree_id, lft
