.github/pull_request_template.md
Ajout du texte d'exemple pour les demandes de fusion
Pour être précis et faciliter la relecture.
Ajout du fichier .md dans le répertoire github.
=> Ajout du template pour demande de fusion

.gitignore
Nettoyage du  fichier `.gitignore`.
Pour plus de lisibilité
En laissant uniquement les lignes nécessaires
=> Nettoyage du fichier `.gitignore`

.github/workflows/ci.yml, Makefile
Gérer les dépendances et les environnements virtuels python localement et dans la CI. 
Le fichier `pyproject.toml` sert de référence pour les dependances de dev et de prod sur ce projet.
La génération des fichiers de requirements requiert l'utilisation d'un binaire qui garantit la cohérence entre ces fichiers et le fichier de référence `pyproject.toml`. Les fichiers de requirements sont automatiquement générés à l'aide d'un hook pre-commit.
L'installation des dépendances dans la CI est gérée via poetry.
L'installation des dépendances localement est laissée au libre choix des dev avec poetry ou pyenv.
- ajout de la variable `USE_VENV` dans le fichier `Makefile` et adaptation des commandes pour gérer les contextes sans poetry
[ ] ajouter un template de pre-commit avec pyenv
=> Rendre la gestion des dependances et des environnements virtuels plus agnostique

.vscode/extensions.json, .vscode/settings.json
dans le titre
pour partager nos setup
=> Versionning des settings vscode

config/settings/base.py, config/urls.py, lacommunaute/forum_member/admin.py, lacommunaute/forum_member/factories.py, lacommunaute/forum_member/models.py, lacommunaute/templates/forum_member/profiles.html, lacommunaute/templates/registration/login.html, lacommunaute/users/factories.py, lacommunaute/www/forum_member/tests.py, lacommunaute/www/forum_member/urls.py, lacommunaute/www/forum_member/views.py
* Gestion par défaut des utilisateurs
* Gestion des profils des membres
* Permettre le login/logout en attendant inclusion connect
* Gerer l'annuaire des membres
* Surcharge du modèle `machina` `forum_member`
* Ajout de la ListView `ForumProfileListView`
* Ajout des factories `User` and `Forum_Member`
* la gestion des avatars sera traitée dans une PR suivante
=> Surcharge du modèle Machina Forum_Member

Makefile
Amélioration du fichier Makefile
- ajout de `fix` pour corriger le code
- ajout de `dependencies` pour générer les fichiers `requirements` et `poetry.lock`
- suppression de la command `rebuild_index` inutile
=> Amélioration du fichier Makefile

lacommunaute/templates/board_base.html, lacommunaute/templates/forum_conversation/topic_detail.html, lacommunaute/templates/layouts/base.html, lacommunaute/templates/partials/header.html, lacommunaute/templates/partials/messages.html
- Mise à jour du layout principal machina pour ajouter rapidement un container centré à tous les templates et sous templates
- Fix des class `alert-*` dans messages.html
- Modification du template qui liste les réponses a post pour mettre le sujet du post en avant
- Suppression de l'import js du thème itou dans le layout principal du forum car erreurs js du à la double injection de function js bootstrap4
=> Update de templates machina

README.md
Ajout de la librairie `factory-boy`
Pour exploiter les factories de `machina`
- ajout d'exemples dans le Readme
=> Activation des factories `machina`

lacommunaute/templates/pages/home.html, poetry.lock
mise à jour temporaire du contenu de la home page
=> mise à jour temporaire du contenu de la home page

lacommunaute/templates/partials/header.html, lacommunaute/templates/partials/header_nav_primary_items.html
Corriger le menu mobile et en profiter pour optimiser
Simplifier la gestion des évolutions du menu desktop et mobile
=> Corriger le menu mobile

lacommunaute/templates/forum_conversation/topic_detail.html, lacommunaute/templates/forum_conversation/topic_list.html
Masque les adresses emails des utilisateurs non connecté
=> Masque les adresses emails des utilisateurs non connecté

lacommunaute/templates/forum_conversation/topic_detail.html
cf titre
Cette page sera de moins en moins accédée, mais des utilisateurs peuvent s'y retrouver par hasard.
- Ajustement des liens éditer/supprimer
- Suppression du pavé "avatar" à droite
=> Simplification de la page machina `topic detail`

lacommunaute/templates/pages/home.html, lacommunaute/templates/partials/header_nav_primary_items.html
Cf titre
Pour être au top !
Correction du texte dans le gabarit.
=> Corrections de texte sur la page d'accueil

lacommunaute/forum/management/commands/fake_contents.py, lacommunaute/users/factories.py
Générer automatiquement des contenus cohérents et utlisables pour les environnements non productifs
Pour tester les fonctionnalités et leurs évolutions
Mise à jour de la factory `UserFactory` pour
1. résoudre le problème d'unicité du username au cas où la command est executée sur un environnement non vierge,
2. permettre la connexion avec le username si besoin (quand inclusion connect n'est pas dispo)
Ajout d'une management command, au lieu de fixtures, pour rendre possible l'execution sur un environnement contenant déjà des données
*Depuis un environnement virtuel python*
```
python manage.py fake_contents
```
*Avec un conteneur docker* 
```
docker exec -it commu_django bash
```
puis dans le shell du conteneur
```
python manage.py fake_contents
```
*Avec poetry*
```
poetry run python …
```
=> Generation de données fictives pour les environnements non productifs

lacommunaute/templates/pages/contact.html, lacommunaute/templates/pages/statistiques.html
Supprimer les "lorem" des pages et uniformisations du message d'attente
Pourquoi pas
=> Suppression des lorem des pages statiques

config/settings/base.py
cf titre
impact sur le deploiement
=> Modification de l'ordre de déclaration des context_processors dans base.py

config/settings/base.py
=> Modification de l'ordre de déclaration des middlewares dans base.py

lacommunaute/utils/settings_context_processors.py
=> Retrait de la gestion de BASE_TEMPLATE dans settings_context_processor

.github/pull_request_template.md
=> proposition de mise à jour du pull_request_template

.github/workflows/review-app-creation.yml, .github/workflows/review-app-removal.yml
Mise en place des recettes jetables
* Ajout des fichiers github actions de création et de suppression des app de recette
* Ajout du label `recette-jetable`
* Création d'un addon clever cloud de type `configuration provider` pour stocker les variables d'environnement
* Mise à jour des `Allowed_Hosts` dans cet addon
* Création d'un addon clever cloud de type `Cellar S3 Storage`
* Création d'un bucket dans cet addon
* Ajout des clés CLEVER_TOKEN et CLEVER_SECRET dans github secrets, obtenus via la commande `clever login`
Depuis le shell de l'app elle-même : 
* obtenir l'uuid de l'app depuis le dashboard clever
* lier l'app avec le client clever
`clever link app_UUID`
* accès à l'app en ssh
`clever ssh -a c3-django-review-NAME`
* naviguer jusqu'au repertoire de l'app
`cd app_*`
* installer …
=> Recette Jetable

lacommunaute/templates/forum/forum_list.html, lacommunaute/templates/layouts/base.html, lacommunaute/templates/partials/footer.html
🎸 Suppression des liens de flux RSS dans les tableaux de communautés.  
Il en a été plusieurs fois questions en réu donc voilà, c'est fait ;)
=> Suppression liens des flux RSS

lacommunaute/forum/factories.py, lacommunaute/forum/tests.py, lacommunaute/forum_conversation/factories.py, lacommunaute/forum_conversation/forum_attachments/factories.py, lacommunaute/forum_conversation/tests/tests_forms.py, lacommunaute/forum_conversation/tests/tests_models.py, lacommunaute/forum_conversation/tests/tests_views.py, lacommunaute/users/factories.py, lacommunaute/utils/tests.py, lacommunaute/www/forum/tests_views.py
🎸 Ajout / Correction de quelques factories
🎸 Suppression des références aux factories `machina` dans les tests
🎸 Utilisation des factories du projet dans les tests
🚧 technique uniquement
=> Nettoyage des tests automatiques

lacommunaute/templates/partials/footer.html, lacommunaute/templates/partials/header.html
🎸 Mise à jour des liens dans le header et le footer, de `communaute.inclusion.beta.gouv.fr `vers `communaute-experimentation.inclusion.beta.gouv.fr`
🦺 Préparation de la fermeture du site WP
=> [WP] Mise à jour des liens dans le header et le footer

lacommunaute/templates/partials/header_nav_primary_items.html
🎸 Application du thème `Inclusion Connect`  au bouton de connection
🖌 design uniquement
=> Mise à jour du bouton de connection

lacommunaute/templates/forum/forum_list.html
Ajustement des espacements entre le titre, la descption et le bouton "voir les sous-commnautés"
Visuel, ui
=> Ajustement des espacements entre le titre, la descption et le bouton "voir les sous-commnautés"

lacommunaute/templates/404.html
🎸 Rendre explicite pourquoi certains liens ne répondent plus, et les aider à se réorienter.
🚧 technique
=> Page 404 suite au changement de nom de domaine

lacommunaute/templates/partials/header_nav_primary_items.html, lacommunaute/users/admin.py, lacommunaute/users/models.py
🎸 Voir et gérer les membres d'un groupe dans l'admin
=> Admin - gestion des groupes

config/settings/base.py, config/settings/dev.py, lacommunaute/utils/settings_context_processors.py, lacommunaute/utils/urls.py, lacommunaute/www/inclusion_connect_views/views.py
🎸 Tenir compte du `host` de l'utilisateur pour gérer les `callback` inclusion connect.
🦺 fix urgent. test a ajouter dans une PR à venir
=> Authentification Inclusion Connect multi-domain

lacommunaute/templates/pages/home.html
🎸 Afficher le formulaire de NPS une fois seulement 
=> Mise à jour des règles d'affichage du formulaire de NPS

.github/workflows/review-app-creation.yml, .github/workflows/review-app-removal.yml
🎸 Mise à jour des paramètres clevercloud pour les `review_apps` suite au changement d'organisation
🚧 technique
🦺   REVIEW_APPS_ORGANIZATION_NAME: ${{ secrets.CLEVER_REVIEW_APPS_ORG }}
🦺   CONFIGURATION_ADDON: ${{ secrets.CLEVER_REVIEW_APPS_CONFIGURATION_ADDON }}
🦺   S3_ADDON: ${{ secrets.CLEVER_REVIEW_APPS_S3_ADDON }}
=> Mise à jour de la configuration des recettes jetables

lacommunaute/templates/event/event_calendar.html, lacommunaute/www/event_views/tests.py, lacommunaute/www/event_views/views.py
🎸 Encoder l'url de redirection pour prise en charge par Inclusion_Connect
🚧 technique
=> Gérer la redirection lors de l'authentification pour créer un nouvel évènement

lacommunaute/templates/pages/statistiques.html
🎸 Mise à jour des statistiques mensuelles pour le mois de mars 2023
🎨 contenu statiques
🦺 non responsive ;)
=> Statistiques mensuelles : mars 2023

lacommunaute/forum_stats/management/commands/collect_events.py
🎸 Extraire dans des fichiers json, le nombre d'evenements par mois et par semaine
🚧 technique
🦺 Source : DB et Matomo
🦺 Ce code devra être refactoré : test + intégration dans la base de code
=> STATS : compter les evenements

CHANGELOG.md, lacommunaute/pages/views.py
🎸 changelog v1.11
:rescue_worker_helmet: des dependances non mises à jour. 
versions incompatibles : `django-4.5.2, anyio-3.7.0, respx-0.20.1, Faker-18.9.0, xdist-3.3.1`
🚧 technique
=>  Changelog v1.11

lacommunaute/templates/pages/home.html
🎸 UX beta test de la page d'accueil
🎨 Design
=> Aligner la page d'accueil avec l'audience cible

lacommunaute/templates/pages/statistiques.html
🎸 Mise à jour la page https://communaute.inclusion.beta.gouv.fr/statistiques/ avec les données de mai 2023
🎨 Mise à jour contenu statique
=> [STATS] stats mensuelles Mai 2023

lacommunaute/event/factories.py, lacommunaute/event/tests/tests_views.py
🎸 gérer les dates et heures de manière dynamiques et dans le futur obligatoirement
🚧 technique
=> [FIX] rendre la factory des évènements résiliente

clevercloud/python.json, config/settings/base.py, config/settings/dev.py
🎸 cf titre. Le déport de l'index dans un bucket S3 pourrait poser des problèmes de performance en plus des problèmes de configuration
🚧 technique
=> [SEARCH] rollback - stockage index localement et reconstruction lors du déploiement

config/settings/base.py, lacommunaute/templates/forum_conversation/topic_detail.html, lacommunaute/templates/partials/footer.html
🎸 Renommange du forum en "La communauté de l'inclusion" (titre des pages) 
🎸 Mise à jour des balises `title` et `description` dans la vue de détail d'un `topic`
🎸 Ajout du lien vers le glossaire (flatpages) dans le footer
🎨 SEO
=> [SEO] boosts

lacommunaute/templates/partials/footer.html
=> [SEO] boost

lacommunaute/templates/pages/statistiques.html
🎸 Mise à jour la page https://communaute.inclusion.beta.gouv.fr/statistiques/ avec les données de juin 2023
🎨 Mise à jour contenu statique
=> [STATS] stats mensuelles Juin 2023

lacommunaute/templates/partials/banner.html
🎸 nouvelle url https://aide.emplois.inclusion.beta.gouv.fr/hc/fr
🚧 technique
=> [forum_conversation] mise à jour du lien vers l'aide des emplois

CHANGELOG.md
🎸 mise à jour du fichier des changements pour la release V2.0
🚧 technique
=> Changelog v2.0

lacommunaute/templates/forum/forum_detail.html
🎸 Mise à jour du titre des liens vers les autres fiches du thème
🎨 UI
=> [DOCUMENTATION] titre des liens vers les autres fiches du thème

lacommunaute/templates/pages/statistiques.html
🎸 Mise à jour des statistiques mensuelles, période Aout 2023
=> [STATISTIQUES] août 2023

lacommunaute/pages/tests/test_mentions_legales.py, lacommunaute/pages/tests/test_politique_confidentialite.py, lacommunaute/pages/urls.py, lacommunaute/pages/views.py, lacommunaute/templates/layouts/base.html, lacommunaute/templates/pages/accessibilite.html, lacommunaute/templates/pages/mentions_legales.html, lacommunaute/templates/pages/politique_de_confidentialite.html, lacommunaute/templates/partials/footer.html, lacommunaute/templates/partials/form_field.html, lacommunaute/templates/partials/form_field_mentions.html
🎸 mentions d'informations
🎸 politique de confidentialité
🎸 mentions légales
🎨 UX
=> [PAGES] mise à jour des pages de mentions 

clevercloud/cron.json
🎸 mise à jour de la planification de `send_notifs_when_following_replies.sh` à 6h UTC
=> [NOTIFICATION] mise à jour de la planification de `send_notifs_when_following_replies.sh`

.pre-commit-config.yaml, poetry.lock, requirements/base.txt, requirements/dev.txt
🎸 mise à jour de dépendances
🚧 technique
=> mise à jour des dependances

lacommunaute/templates/forum_conversation/forum_attachments/attachments_detail.html
=> rollback [DEV] fichiers manquants

config/settings/base.py
Description
🦺 autoriser explicitement https://cdn.jsdelivr.net/npm/chart.js@4.0.1
🚧 technique
=> Content Security Policies - patch 3

.env.template, scripts/import-latest-db-backup.sh
🎸adaptation du scripts de rechargement des sauvegardes de DB suite à la mise à jour de [itou-backups](https://github.com/betagouv/itou-backups/pull/27)
🚧 technique
🦺 telecharger la sauvegarde avec `rclone` avant de lancer le rechargement
=> Chargement d'une sauvegarde de base de données

lacommunaute/templates/forum_search/search_form.html, lacommunaute/templates/partials/header_nav_primary_items.html
🎸 pour leur suivi dans `matomo` 
🚧 technique
=> [STATS] nommage des formulaires de recherche

lacommunaute/forum/tests/tests_views.py, lacommunaute/templates/event/event_form.html, lacommunaute/templates/event/event_list.html, lacommunaute/templates/forum/category_forum_list.html, lacommunaute/templates/forum/forum_list.html, lacommunaute/templates/forum_conversation/forum_polls/topic_list_poll_detail.html, lacommunaute/templates/forum_conversation/forum_polls/topic_list_poll_vote_form.html, lacommunaute/templates/forum_conversation/partials/post_certified.html, lacommunaute/templates/forum_conversation/partials/post_certified_actions.html, lacommunaute/templates/forum_conversation/partials/poster.html, lacommunaute/templates/forum_conversation/partials/topic_filter.html, lacommunaute/templates/forum_conversation/partials/topic_form.html, lacommunaute/templates/forum_member/forum_profile_detail.html, lacommunaute/templates/forum_member/moderator_profiles.html, lacommunaute/templates/forum_member/profiles.html, lacommunaute/templates/forum_search/search.html, lacommunaute/templates/forum_upvote/upvote_list.html, lacommunaute/templates/pages/contact.html, lacommunaute/templates/partials/ask_a_question.html, lacommunaute/templates/partials/banner.html, lacommunaute/templates/partials/footer.html, lacommunaute/templates/partials/upvotes.html
🎸 reindentation des gabarits du projet
🎸 mise à jour du test sur le gabarit `upvote.html` pour le rendre résilient face aux reindentations
🚧 technique
=> qualité - reindexation des gabarits

lacommunaute/forum_stats/models.py, lacommunaute/forum_stats/tests.py, lacommunaute/pages/tests/tests.py, lacommunaute/pages/views.py, lacommunaute/templates/pages/statistiques.html, lacommunaute/utils/math.py, lacommunaute/utils/tests.py
🎸 Exploiter les données en DB pour valoriser les stats de l'entonnoir
🚧 technique
=> [STATS] des données dynamiques dans l'entonnoir

lacommunaute/forum_search/search_indexes.py, lacommunaute/forum_search/tests/test_search_indexes.py
🎸 Ne pas afficher les `Post` et `Forum` privés
=> [SEARCH] limiter l'indexation aux contenus publics

lacommunaute/templates/pages/home.html
=> [NPS FORM] délai avant affichage sur la homepage à 10secondes

.github/workflows/ci.yml, .github/workflows/review-app-creation.yml, docker-compose.yml
🎸 Montée de version PG 15
🚧 technique
🦺 CI
🦺 review app
🦺 image docker (+version docker-compose 3.8)
=> [DB] montée en version 15

CHANGELOG.md
=> changelog v2.4

Makefile
🎸 ajout d'un commentaire pour le telechargement de la dernière sauvegarde DB
🚧 technique
=> [Makefile] ajout commentaire RCLONE

lacommunaute/templates/pages/home.html
🎸 ajout d'un emoji sur la home
🚧 technique
=> Test deploiement automatique après bascule du repo

lacommunaute/templates/pages/accessibilite.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Landing-du-GIP-R-daction-sch-ma-pluriannuel-d-accessibilit-bonus-c48c04fa863442119fdf63fbe41bc798?pvs=4
Mise à jour du contenu de la déclaration d'accessibilité afin d'ajouter le paragraphe concernant le schéma pluriannuel du GIP
=> Mise a jour du contenu de la déclaration d'accessibilité

lacommunaute/templates/event/event_detail.html
🎸 Ajout du nom de l'evenement dans le titre de la page
🎸 SEO
🎨 UI
=> [evenements] correction du titre de la page de détail

lacommunaute/templates/layouts/base.html
🎸 ajout du tag manager matomo 
🚧 technique
=> ajout du tag manager matomo

.vscode/settings.json
🎸 mise à jour des settings vscode
🚧 technique
=> (settings) update vscode settings

.pre-commit-config.yaml, CHANGELOG.md, poetry.lock, requirements/base.txt, requirements/dev.txt, scripts/changelog.py
🎸 Journal des changements v2.5
🛸 mise à jour des dépendances
🚧 technique
=> Changelog v2.5

lacommunaute/templates/layouts/base.html, lacommunaute/templates/pages/statistiques.html
⚠️ quick fix sans précommit.
🚧 technique
🦺 `djlint` ne gère pas correctement les blocks de script
🦺 TODO NEXT : corriger le precommit
=> Quality - urgent fix - Reformattage erronée des blocks de scripts dans les gabarits

lacommunaute/utils/matomo.py, lacommunaute/utils/tests.py
=> [STATS] ajout du nombre d'utilisateurs retours dans l'extraction matomo

lacommunaute/templates/forum_conversation/partials/topic_filter.html
=> Fix typo Filter → Filtrer

lacommunaute/forum_conversation/tests/tests_views.py
Correction d’un échec de test intermittent.
🚧 technique
=> Fix flaky test_showmoretopics_url_with_params

lacommunaute/forum_search/tests/test_search_indexes.py
Les tests échouaient de manière intermittente.
🚧 technique
Fixes #479
=> Correction des échecs intermittents de tests_search_indexes

lacommunaute/templates/pages/home.html
🎸 passage à 90sec 
🚧 technique
=> [HOMEPAGE] delai d'affichage popup

lacommunaute/templates/pages/home.html, lacommunaute/templates/partials/promotion_banner.html
🎸 cf titre
🚧 technique
🦺 `templates/partials/promotion_banner.html`
=> [HOMEPAGE] isoler la bannière de promotion dans un gabarit spécifique

lacommunaute/templates/partials/promotion_banner.html
🎸 mise à jour bannière. visible jusqu'au 26.02.
🎨 UI
=> [HOMEPAGE] bannière inclusion-demain

lacommunaute/templates/pages/home.html
🎸 fix : rendre le javascript de l'AB Testing compatible avec les règles CSP
🚧 technique
=> [HOMEPAGE] CSP x AB Test

lacommunaute/templates/pages/home.html, lacommunaute/templates/partials/ask_a_question.html
🎸 cf #499 sans utiliser la redirection
- http://127.0.0.1:8000/?pk_ab_test=original
- http://127.0.0.1:8000/?pk_ab_test=btn_plein
- http://127.0.0.1:8000/?pk_ab_test=btn_outlined
=> [HOMEPAGE] AB test fréquentation de la page documentation

lacommunaute/forum/factories.py
=> Corriger les échecs intermittents de ForumViewTest.test_queries

lacommunaute/templates/404.html
🎸 Mise à jour du contenu, suppression des liens cassés
=> Mise à jour de la page 404

lacommunaute/templates/404.html
=>  Mise à jour de la page 404 (fix)

Makefile
=> Retirer les alias et règles inutilisées du Makefile

.github/workflows/ci.yml
Be easier on PyPI by making less requests.
=> Mettre en cache les paquets Python

.github/workflows/ci.yml
C’est la version utilisée en prod.
=> Tester sur Python 3.11

lacommunaute/pages/urls.py, lacommunaute/pages/views.py
=> Retrait de la vue Sentry trigger_error (non utilisée)

lacommunaute/forum_conversation/views_htmx.py
=> Correction d’une typo (double assignement)

config/settings/base.py, lacommunaute/utils/settings_context_processors.py
=> Retirer ALLOWED_HOSTS des context processors

config/settings/base.py, lacommunaute/templates/layouts/base.html
=> Surveiller les erreurs JS avec Sentry

config/settings/base.py, poetry.lock, pyproject.toml
https://docs.djangoproject.com/en/5.0/releases/5.0/
🚧 technique
Fixes #523
=> Mise à jour vers Django 5.0

clevercloud/python.json
=> Ne pas forcer la compression au déploiement

poetry.lock, requirements/base.txt, requirements/dev.txt
🛸 mise à jour
🚧 technique
🦺 Django 5.0.2
🦺 Prerequis pour #548
=> Mise à jour des dépendances

CHANGELOG.md
=> changelog v2.6

lacommunaute/templates/surveys/dsp_form.html
=> [DSP] typo

lacommunaute/utils/templatetags/theme_inclusion.py
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#type
https://github.com/django/django/commit/7c4f3965098baad2396e24501e09237425a7bd6f
=> Remove text/css from stylesheet links and style

lacommunaute/pages/tests/test_homepage.py, lacommunaute/pages/views.py, lacommunaute/templates/pages/home.html, lacommunaute/templates/partials/footer.html, lacommunaute/templates/partials/header_nav_secondary_items.html
=> [HOMEPAGE] retrait du fil des actualités

lacommunaute/templates/pages/statistiques.html
🎸 suppression des utilisateurs actifs quotidiens
🎸 ajout des propriétés de couleurs sur les graphes
=> [STATS] suppression des utilisateurs actifs quotidiens

lacommunaute/forum_member/tests/tests_view.py, lacommunaute/templates/forum_member/forum_profile_detail.html
🎸 afficher le lien vers le profil linkedin dans `ForumProfileDetailView` si celui-ci est renseigné.
🎨 UI
=> [MEMBER] afficher le lien vers le profil linkedin

lacommunaute/forum/forms.py
🎸 suite de #593
🎸 labels, et textarea
🎨 UI
=> [DOCUMENTATION] rendre le formulaire de creation des fiches pratiques plus explicite

.github/workflows/semantic-pr.yml
🎸 mise en place https://github.com/marketplace/actions/semantic-pull-request
🚧 technique
=> [TECH] PR semantique

.github/workflows/pr-auto-author-assign.yml
🎸 mise en place https://github.com/marketplace/actions/auto-author-assign
🚧 technique
=> ci: auto assignation des PR

poetry.lock, requirements/base.txt, requirements/dev.txt
🛸 dependabot warning sur sqlparse
🚧 technique
🦺 django 5.0.4
=> chore: mise à jour des dépendances

CHANGELOG.md, poetry.lock, requirements/base.txt, requirements/dev.txt
🎸 Changelog v2.8
🛸 Mise à jour des dépendances
🚧 technique
=> chore: Mise à jour des dépendances & journal des changements version 2.8

.github/workflows/release-please.yml
🎸 automatisation de la gestion des releases et du changelog
🚧 technique
=> ci: mise en place de release-please

README.md
🎸 mise à jour de `python manage.py populate` pour peupler la DB
🚧 technique
=> chore: mise à jour du Readme

.github/workflows/release-please.yml
🎸 correction de la déclaration du token dans l'action github `release-please`
🚧 technique
=> fix: release-please token

.github/pull_request_template.md
🎸 Mise à jour du gabarit des demandes de tirage
🚧 technique
=> fix: mise à jour du gabarit de PR

lacommunaute/forum_conversation/admin.py
🎸 Ajoute une class `Inline` pour les messages sur un Topic
=> feat(admin): ajoute PostInline à TopicAdmin

lacommunaute/templates/forum/forum_detail.html
=> feat(forum): Activation de l'AB Test Notation des forums

lacommunaute/templates/forum/forum_detail.html
🎸 correction `id` de la zone mise à jour
🦺 pour tester en local 
* http://127.0.0.1:8000/forum/conception-dun-atelier-favorisant-linsertion-professionnelle-des-publics-141/?pk_ab_test=original
* http://127.0.0.1:8000/forum/conception-dun-atelier-favorisant-linsertion-professionnelle-des-publics-141/?pk_ab_test=rating_area_2
* http://127.0.0.1:8000/forum/conception-dun-atelier-favorisant-linsertion-professionnelle-des-publics-141/?pk_ab_test=rating_area_3
=> fix(forum): ab test forum rating

lacommunaute/templates/pages/home.html, lacommunaute/templates/partials/footer.html
🎸 mise à jour libellé 'fiches pratique'
🎸 mise à jour pied de page
=> feat(home): petites améliorations

lacommunaute/stats/admin.py
🎸 suite #699
🚧 technique
🦺 amélioration `lookups`
=> feat(admin): filtrage des stats de forum, ajout tri

lacommunaute/forum/factories.py, lacommunaute/surveys/factories.py, lacommunaute/users/factories.py
🎸 Mise à jour du paramètre `._after_postgeneration` des factories du projet
🚧 technique
=> chore: suppression des deprecation warning sur factory_boy

lacommunaute/templates/layouts/base.html
🛸 mise à jour du chargement du script js sentry
🚧 technique
=> chore: mise à jour de la version du script js sentry

lacommunaute/templates/partials/footer.html
🎸 mise à jour des liens X.com, FB, YT
🎸 suppression lien instagram
=> feat(footer): mise à jour des liens sociaux

lacommunaute/event/admin.py
🎸 Ajout de filtres, de tris et du champ de recherche dans l'interface admin des `Event`
🚧 technique
=> feat(event): amélioration de l'admin

lacommunaute/partner/tests/__snapshots__/tests_partner_listview.ambr, lacommunaute/static/stylesheets/itou_communaute.scss, lacommunaute/templates/partner/list.html
=> fix(partner): mise en forme des logos de la vue en liste

lacommunaute/templates/layouts/base.html
🎸 sondage Tally en mode popup. déclenchement après scroll d'au moins 15% de la page.
🦺 script sur `base.html`
=> feat: ajout d'un sondage pour mieux connaitre les utilisateurs de la communauté

lacommunaute/templates/layouts/base.html
=> feat: suppression du sondage pour mieux connaitre les utilisateurs de la communauté

lacommunaute/utils/templatetags/str_filters.py
🎸 log pollution because of a print in `youtube_embed`
🚧 technique
=> fix(log): patch #810

lacommunaute/templates/layouts/base.html
🎸 mise à jour UI de la banniere `dev mode`
🚧 technique
=> chore: login in debug/dev mode - UI update

lacommunaute/templates/pages/politique_de_confidentialite.html
🎸 mise à jour de la page [politique de confidentialité](https://communaute.inclusion.beta.gouv.fr/politique-de-confidentialite/)
=> feat: mise à jour de la politique de confidentialité

lacommunaute/templates/registration/login_with_magic_link.html, lacommunaute/users/tests/__snapshots__/tests_views.ambr
🎸 ajout d'un texte explicatif  au dessus du bouton pro connect
=> feat: amélioration bouton pro_connect

lacommunaute/users/tests/tests_views.py
🎸 `TestSendMagicLink`
🚧 technique
🦺 forcer le token à `fixed-token` pour tester son affichage
=> refactor: correction d'un test fragile

clevercloud/python.json
=> chore: correction de la mise en cache des dépendances dans clever cloud

lacommunaute/templates/layouts/base.html, lacommunaute/utils/tests/tests_middleware.py
🎸 empecher l'affichage en production de la banniere `DEV MODE` en cas d'erreur 500
🎸 améliorer le test de l'expositions des `settings` par le `context processor`
🚧 technique
=> chore: dev mode banner fixes

pyproject.toml, uv.lock
=> chore: mise à jour Django, version 5.1.5

lacommunaute/templates/layouts/base.html, lacommunaute/utils/tests/__snapshots__/tests_context_processor.ambr, lacommunaute/utils/tests/tests_context_processor.py
🎸 cf title
🚧 technique
dev local
review app
=> chore: afficher la bannière d'environnement systématiquement hors PROD

lacommunaute/pages/tests/tests.py, lacommunaute/pages/views.py, lacommunaute/templates/partials/header.html
🎸 accès à la liste des landing-pages
🎸 accès aux écrans de gestion des fichiers publics
🎸 accès aux écrans de gestion des pages statiques
Utile pour les changements liés à l'UI.
=> feat: extension des droits des utilisateurs de l'équipe

clevercloud/cron.json, lacommunaute/users/management/commands/add_missyou_notifications.py, lacommunaute/users/tests/tests_management_commands.py
🎸 cf titre
🦺 replanification de la tâche `cron`
=> fix: mise à jour de la date d'envoi de la notification "vous-nous-manquez"

uv.lock
Reverts gip-inclusion/itou-communaute-django#970
=> Revert "requirement: bump django-csp from 3.8 to 4.0"

config/settings/base.py, config/settings/dev.py, lacommunaute/templates/layouts/base.html, lacommunaute/utils/templatetags/theme_inclusion.py, uv.lock
Mise à jour de la bibliothèque. La configuration de la dernière version étant très différente, elle a dû être réécrite.
[Guide de migration](https://django-csp.readthedocs.io/en/latest/migration-guide.html)
=> Montée de version django_csp

lacommunaute/forum_conversation/tests/tests_views.py, lacommunaute/forum_moderation/tests/test_utils.py, lacommunaute/forum_moderation/utils.py
[Cette erreur](https://inclusion.sentry.io/issues/15300446/) est apparue plus de 17 000 fois ces 90 derniers jours,
par à-coups, probablement dû à quelques attaques de SPAM.
=> Correction erreur LangDetectException

lacommunaute/forum_conversation/migrations/0006_topic_tags.py, lacommunaute/forum_conversation/models.py
=> Rendre l’étiquette d’un sujet optionnelle

.github/workflows/ci.yml, .gitignore, docker-compose.yml, docs/TODO.md
Utilisation de l’image officielle en dev
Utilisation de bitnamylegacy/minio pour la CI, car https://stackoverflow.com/a/61036320
=> Mise à jour de l’utilitaire S3 suite à l’arrêt de bitnami/minio
